export const FLAGS = [
  'VisAvslagsaarsaker',
  'TilbakekrevingBelopFilter',
  'VisArenasakerOversikt',
  'ArenasakerLenkeTilVisninsklient',
  'BegrunnelseForIkkeSendBrev',
  'ReturAarsakJournalforing',
  'VisValgForDialogmelding',
  'HentFastlege',
  'OppgavelisteMedBelopISaksbehandling',
  'KravSteg',
  'BeregningstidspunktAarsak',
  'VentStatusForTilbakekreving',
  'VisMigrereSakFraArenaKnapp',
  'KvalitetssikringDiff',
  'Avslag11_27',
  'NyHookForAvklaringsbehov',
  'SkalViseAlleSykdomssteg',
  'DialogMedBehandler',
  'VedtakslengdeAarsak',
] as const;

export type FlagNames = (typeof FLAGS)[number];
export type Flags = Record<FlagNames, boolean>;

export const mockedFlags: Flags = {
  VisAvslagsaarsaker: true,
  TilbakekrevingBelopFilter: true,
  VisArenasakerOversikt: true,
  ArenasakerLenkeTilVisninsklient: true,
  BegrunnelseForIkkeSendBrev: true,
  ReturAarsakJournalforing: true,
  VisValgForDialogmelding: true,
  HentFastlege: true,
  OppgavelisteMedBelopISaksbehandling: true,
  KravSteg: true,
  BeregningstidspunktAarsak: true,
  VentStatusForTilbakekreving: true,
  VisMigrereSakFraArenaKnapp: true,
  KvalitetssikringDiff: true,
  Avslag11_27: true,
  NyHookForAvklaringsbehov: true,
  SkalViseAlleSykdomssteg: true,
  DialogMedBehandler: true,
  VedtakslengdeAarsak: true,
};
