export const FLAGS = [
  'VisAvslagsaarsaker',
  'TilbakekrevingBelopFilter',
  'VisArenasakerOversikt',
  'ArenasakerLenkeTilVisninsklient',
  'ReturAarsakJournalforing',
  'VisValgForDialogmelding',
  'HentFastlege',
  'StudentV2',
  'OppgavelisteMedBelopISaksbehandling',
  'KravSteg',
  'BeregningstidspunktAarsak',
  'VentStatusForTilbakekreving',
  'VisMigrereSakFraArenaKnapp',
  'Avslag11_27',
  'SkalViseAlleSykdomssteg',
  'DialogMedBehandler',
  'FaktiskArbeidTilkjentYtelse',
  'kopierPerioder',
  'autoSplittSykepenger',
] as const;

export type FlagNames = (typeof FLAGS)[number];
export type Flags = Record<FlagNames, boolean>;

export const mockedFlags: Flags = {
  VisAvslagsaarsaker: true,
  TilbakekrevingBelopFilter: true,
  VisArenasakerOversikt: true,
  ArenasakerLenkeTilVisninsklient: true,
  ReturAarsakJournalforing: true,
  VisValgForDialogmelding: true,
  StudentV2: true,
  HentFastlege: true,
  OppgavelisteMedBelopISaksbehandling: true,
  KravSteg: true,
  BeregningstidspunktAarsak: true,
  VentStatusForTilbakekreving: true,
  VisMigrereSakFraArenaKnapp: true,
  Avslag11_27: true,
  SkalViseAlleSykdomssteg: true,
  DialogMedBehandler: true,
  FaktiskArbeidTilkjentYtelse: true,
  kopierPerioder: true,
  autoSplittSykepenger: true,
};
