nodeLinker: node-modules

npmMinimalAgeGate: 2880
npmPreapprovedPackages:
  - "@navikt/aap-oppgave-typescript-types"
  - "@navikt/aap-postmottak-backend-typescript-types"
  - "@navikt/aap-statistikk-typescript-types"

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"

# Sikkerhetstiltak
enableScripts: false # Forhindre kjøring av scripts ved installasjon av pakker
enableImmutableInstalls: true # Sikre at installasjoner er konsistente med lockfilen
defaultSemverRangePrefix: "" # Bruk eksakte versjoner av pakker som standard (ikke "^x.x.x")