nodeLinker: node-modules

npmMinimalAgeGate: 2880

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"

# Sikkerhetstiltak
enableScripts: false # Forhindre kjøring av scripts ved installasjon av pakker
defaultSemverRangePrefix: "" # Bruk eksakte versjoner av pakker som standard (ikke "^x.x.x")