apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
  name: "saksbehandling"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  ingresses:
    - "https://kelvin.ansatt.dev.nav.no"
    - "https://kelvin.intern.dev.nav.no"
  port: 3000
  liveness:
    path: "/saksbehandling/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/saksbehandling/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  accessPolicy:
    outbound:
      rules:
        - application: "behandlingsflyt"
        - application: "oppgave"
        - application: "postmottak-backend"
        - application: "statistikk"
        - application: "saksbehandling-pdfgen"
        - application: "dokumentinnhenting"
      external:
        - host: "cdn.nav.no"
  env:
#    - name: NEXT_PUBLIC_ENVIRONMENT
#      value: dev
    - name: ASSET_PREFIX
      value: https://cdn.nav.no/aap/aap-saksbehandling
    - name: BEHANDLING_API_BASE_URL
      value: http://behandlingsflyt
    - name: BEHANDLING_API_SCOPE
      value: api://dev-gcp.aap.behandlingsflyt/.default
    - name: BEHANDLING_API_AUDIENCE
      value: dev-gcp:aap:behandlingsflyt
    - name: SAKSBEHANDLING_PDFGEN_URL
      value: http://saksbehandling-pdfgen
    - name: OPPGAVE_API_BASE_URL
      value: http://oppgave
    - name: OPPGAVE_API_SCOPE
      value: api://dev-gcp.aap.oppgave/.default
    - name: DOKUMENTMOTTAK_API_BASE_URL
      value: http://postmottak-backend
    - name: DOKUMENTMOTTAK_API_SCOPE
      value: api://dev-gcp.aap.postmottak-backend/.default
    - name: STATISTIKK_API_BASE_URL
      value: http://statistikk
    - name: STATISTIKK_API_SCOPE
      value: api://dev-gcp.aap.statistikk/.default
    - name: NEXT_PUBLIC_FARO_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
    - name: OPPGAVESTYRING_FRONTEND_HOST
      value: aap-oppgavestyring.ansatt.dev.nav.no