apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
  name: "saksbehandling"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  ingresses:
    - "https://kelvin.ansatt.dev.nav.no"
    - "https://kelvin.intern.dev.nav.no"
  port: 3000
  liveness:
    path: "/saksbehandling/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/saksbehandling/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  envFrom:
    - secret: kelvin-env-local
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: "behandlingsflyt"
        - application: "oppgave"
        - application: "postmottak-backend"
        - application: "statistikk"
        - application: "saksbehandling-pdfgen"
        - application: "dokumentinnhenting"
      external:
        - host: "cdn.nav.no"
