apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
  name: saksbehandling
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  port: 3000
  liveness:
    path: /actuator/live
    initialDelay: 20
    timeout: 60
  readiness:
    path: /actuator/ready
    initialDelay: 20
    timeout: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          {{#each groups}}
          - id: {{this}}
          {{/each}}
    sidecar:
      enabled: true
      autoLogin: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  envFrom:
    - secret: kelvin-unleash-api-token
  accessPolicy:
    outbound:
      rules:
        - application: behandlingsflyt
        - application: oppgave
        - application: postmottak-backend
        - application: statistikk
        - application: saksbehandling-pdfgen
        - application: dokumentinnhenting
        - application: tilgang
        - application: familie-endringslogg
          namespace: teamfamilie
      external:
        - host: cdn.nav.no
        - host: aap-unleash-api.nav.cloud.nais.io
