/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/oppdater-oppgaver': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.BehandlingFlytStoppetHendelse'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oppdater-postmottak-oppgaver': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.postmottak.kontrakt.hendelse.DokumentflytStoppetHendelse'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oppdater-tilbakekreving-oppgaver': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.TilbakekrevingsbehandlingOppdatertHendelse'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plukk-oppgave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.plukk.PlukkOppgaveRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.plukk.PlukkOppgaveResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/avreserver-oppgaver': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.plukk.AvreserverOppgaveDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.OppgaveId'][];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mottatt-dokumenter-lest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.mottattdokument.DokumenterLestDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/fjern-helseopplysning-ikon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.mottattdokument.DokumenterLestDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/saksbehandler-sok': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.tildel.SaksbehandlerS\u00F8kRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.tildel.SaksbehandlerS\u00F8kResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tildel-oppgaver': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.tildel.TildelOppgaveRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.tildel.TildelOppgaveResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{referanse}/tildelt-status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.tildel.TildeltStatusDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{saksnummer}/hent-oppgaver-paa-sak': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description saksnummer */
          saksnummer: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.hent.OppgaverP\u00E5SakResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{referanse}/hent-saksnummer': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.hent.SaksnummerResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{referanse}/hent-oppgave-visningsinformasjon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.hent.OppgaveVisningsinformasjonResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/oppgaveliste': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.liste.OppgavelisteRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.liste.OppgavelisteRespons'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{referanse}/hent-oppgave-enhet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.enhet.OppgaveEnhetResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mine-oppgaver': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          /** @description Vis kun på vent-oppgaver. */
          kunPaaVent?: boolean;
          /** @description Sorter oppgaveliste */
          sortby?:
            | 'AVKLARINGSBEHOV_KODE'
            | 'BEHANDLINGSTYPE'
            | 'BEHANDLING_OPPRETTET'
            | 'OPPRETTET_TIDSPUNKT'
            | 'PERSONIDENT'
            | 'RESERVERT_AV'
            | 'SAKSNUMMER'
            | 'TILBAKEKREVINGS_BELOP'
            | 'ÅRSAK_TIL_OPPRETTELSE';
          /** @description Sorteringsrekkefølge */
          sortorder?: 'ASC' | 'DESC';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.liste.OppgavelisteRespons'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sok': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.s\u00F8k.S\u00F8kRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.s\u00F8k.S\u00F8kResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{referanse}/opprett-markering-hendelse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.markering.OpprettMarkeringDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.behandling.BehandlingReferanse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{saksnummer}/hent-markeringer-og-historikk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description saksnummer */
          saksnummer: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.markering.MarkeringOgHistorikk'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{referanse}/hent-gjeldende-markeringer-for-behandling': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.markering.MarkeringDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mine-siste-oppgaver': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.SakOgAvklaringsbehov'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/filter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          /** @description Enhetsfilter */
          enheter?: string[];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.filter.FilterResponse'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/enhet/status/person': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.enhet.PersonRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.enhet.EnhetOgOversendelse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/enheter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.enhet.EnhetDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/enhet/nay/person': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.enhet.EnhetForPersonRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.enhet.EnhetNrDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/synkroniser-enhet-paa-oppgave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.enhet.EnhetSynkroniseringRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.enhet.EnhetSynkroniseringRespons'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/feilende': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/feilende/antall': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': number;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/planlagte-jobber': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/{jobbId}/kjor': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/{jobbId}/leggTilKommentar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.motor.api.`MotorApiKt$motorApi$1$5$LeggTilKommentarRequest`'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.Kommentar'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/rekjor/{jobbId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/avbryt/{jobbId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.motor.api.`MotorApiKt$motorApi$1$7$AvbrytJobbRequest`'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/avbrytAlleFeilede': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/rekjorAlleFeilede': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/sisteKj\u00F8rte': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/drift/oppgave/behandling/{referanse}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.drift.OppgaveDriftsinfoDTO'][];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/drift/filter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.drift.DriftFilterResponsDTO'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.drift.FilterDriftRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.oppgave.drift.FilterDriftResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/drift/filter/slett': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.oppgave.drift.SlettFilterRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'no.nav.aap.behandlingsflyt.kontrakt.avklaringsbehov.Definisjon': {
      /** @enum {string} */
      kode:
        | '4101'
        | '4102'
        | '4201'
        | '4301'
        | '5001'
        | '5002'
        | '5003'
        | '5004'
        | '5005'
        | '5006'
        | '5007'
        | '5008'
        | '5009'
        | '5010'
        | '5011'
        | '5012'
        | '5013'
        | '5014'
        | '5015'
        | '5016'
        | '5017'
        | '5018'
        | '5019'
        | '5020'
        | '5021'
        | '5022'
        | '5023'
        | '5024'
        | '5025'
        | '5026'
        | '5027'
        | '5028'
        | '5029'
        | '5030'
        | '5031'
        | '5032'
        | '5033'
        | '5034'
        | '5035'
        | '5036'
        | '5037'
        | '5038'
        | '5039'
        | '5040'
        | '5041'
        | '5042'
        | '5050'
        | '5051'
        | '5052'
        | '5053'
        | '5054'
        | '5056'
        | '5057'
        | '5058'
        | '5059'
        | '5060'
        | '5096'
        | '5097'
        | '5098'
        | '5099'
        | '5999'
        | '6000'
        | '6001'
        | '6002'
        | '6003'
        | '6004'
        | '6005'
        | '6006'
        | '6007'
        | '6008'
        | '6009'
        | '6010'
        | '7001'
        | '8001'
        | '8002'
        | '8003'
        | '8004'
        | '9001'
        | '9002'
        | '9003'
        | '9004'
        | '9082'
        | '9083';
      kreverToTrinn: boolean;
      kvalitetssikres: boolean;
      'l\u00F8sesAv': (
        | 'BESLUTTER'
        | 'DRIFT'
        | 'KVALITETSSIKRER'
        | 'LES'
        | 'PRODUKSJONSSTYRING'
        | 'SAKSBEHANDLER_NASJONAL'
        | 'SAKSBEHANDLER_OPPFOLGING'
      )[];
      /** @enum {string} */
      'l\u00F8sesISteg':
        | 'ARBEIDSOPPTRAPPING'
        | 'AVBRYT_AKTIVITETSPLIKTBEHANDLING'
        | 'AVBRYT_REVURDERING'
        | 'AVKLAR_MIGRERINGSDATO'
        | 'AVKLAR_OPPFØLGING'
        | 'AVKLAR_STUDENT'
        | 'AVKLAR_STUDENT_V2'
        | 'AVKLAR_STØNADSPERIODE'
        | 'AVKLAR_SYKDOM'
        | 'BARNETILLEGG'
        | 'BEHANDLENDE_ENHET'
        | 'BEKREFT_VURDERINGER_OPPFØLGING'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'BREV'
        | 'DU_ER_ET_ANNET_STED'
        | 'EFFEKTUER_11_7'
        | 'ETABLERING_EGEN_VIRKSOMHET'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_BEREGNINGSTIDSPUNKT'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_MELDEPERIODER'
        | 'FASTSETT_RETTIGHETSTYPE'
        | 'FASTSETT_SYKDOMSVILKÅRET'
        | 'FASTSETT_UTTAK'
        | 'FASTSETT_VEDTAKSLENGDE'
        | 'FATTE_VEDTAK'
        | 'FORESLÅ_VEDTAK'
        | 'FORESLÅ_VEDTAK_VEDTAKSLENGDE'
        | 'FORMKRAV'
        | 'FRITAK_MELDEPLIKT'
        | 'FULLMEKTIG'
        | 'IKKE_OPPFYLT_MELDEPLIKT'
        | 'IVERKSETT_BRUDD'
        | 'IVERKSETT_KONSEKVENS'
        | 'IVERKSETT_VEDTAK'
        | 'KLAGEBEHANDLING_KONTOR'
        | 'KLAGEBEHANDLING_NAY'
        | 'KLAGEBEHANDLING_OPPSUMMERING'
        | 'KRAV'
        | 'KVALITETSSIKRING'
        | 'MANGLENDE_LIGNING'
        | 'OMGJØRING'
        | 'OPPRETTHOLDELSE'
        | 'OPPRETT_REVURDERING'
        | 'OVERGANG_ARBEID'
        | 'OVERGANG_UFORE'
        | 'PÅKLAGET_BEHANDLING'
        | 'REFUSJON_KRAV'
        | 'SAMORDNING_ANDRE_STATLIGE_YTELSER'
        | 'SAMORDNING_ARBEIDSGIVER'
        | 'SAMORDNING_AVSLAG'
        | 'SAMORDNING_BARNEPENSJON'
        | 'SAMORDNING_GRADERING'
        | 'SAMORDNING_SYKESTIPEND'
        | 'SAMORDNING_TJENESTEPENSJON_REFUSJONSKRAV'
        | 'SAMORDNING_UFØRE'
        | 'SEND_FORVALTNINGSMELDING'
        | 'SIMULERING'
        | 'START_BEHANDLING'
        | 'START_OPPFØLGINGSBEHANDLING'
        | 'SVAR_FRA_ANDREINSTANS'
        | 'SYKDOMSVURDERING_BREV'
        | 'SØKNAD'
        | 'TREKK_KLAGE'
        | 'UDEFINERT'
        | 'VIS_GRUNNLAG'
        | 'VURDER_AKTIVITETSPLIKT_11_7'
        | 'VURDER_AKTIVITETSPLIKT_11_9'
        | 'VURDER_ALDER'
        | 'VURDER_AVSLAG_11_27'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_INNTEKTSBORTFALL'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'VURDER_OPPHOLDSKRAV'
        | 'VURDER_RETTIGHETSPERIODE'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'VURDER_YRKESSKADE';
      'm\u00E5RevurderesEtterOpph\u00F8r': boolean;
      /** @enum {string} */
      type: 'BREV' | 'BREV_VENTEPUNKT' | 'MANUELT_FRIVILLIG' | 'MANUELT_PÅKREVD' | 'OVERSTYR' | 'VENTEPUNKT';
      /** @enum {string|null} */
      'vurdererVilk\u00E5r'?:
        | 'AKTIVITETSPLIKT'
        | 'ALDERSVILKÅRET'
        | 'BISTANDSVILKÅRET'
        | 'GRUNNLAGET'
        | 'INNTEKTSBORTFALL'
        | 'LOVVALG'
        | 'MEDLEMSKAP'
        | 'OPPHOLDSKRAV'
        | 'ORDINÆR_KVOTE'
        | 'OVERGANGARBEIDVILKÅRET'
        | 'OVERGANGUFØREVILKÅRET'
        | 'SAMORDNING'
        | 'SAMORDNING_ANNEN_LOVGIVNING'
        | 'STRAFFEGJENNOMFØRING'
        | 'STUDENT'
        | 'SYKDOMSVILKÅRET'
        | 'SYKEPENGEERSTATNING'
        | 'SYKEPENGEERSTATNING_KVOTE'
        | null;
      name: string;
    };
    /** Format: uuid */
    'no.nav.aap.behandlingsflyt.kontrakt.behandling.BehandlingReferanse': string;
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvklaringsbehovHendelseDto': {
      avklaringsbehovDefinisjon: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.avklaringsbehov.Definisjon'];
      endringer: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.EndringDTO'][];
      /** Format: int64 */
      id?: number | null;
      /** @enum {string} */
      status:
        | 'AVBRUTT'
        | 'AVSLUTTET'
        | 'KVALITETSSIKRET'
        | 'OPPRETTET'
        | 'SENDT_TILBAKE_FRA_BESLUTTER'
        | 'SENDT_TILBAKE_FRA_KVALITETSSIKRER'
        | 'TOTRINNS_VURDERT';
    };
    /** Format: uuid */
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvvistLegeerkl\u00E6ringId': string;
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.BehandlingFlytStoppetHendelse': {
      /** @enum {string|null} */
      aktivtSteg?:
        | 'ARBEIDSOPPTRAPPING'
        | 'AVBRYT_AKTIVITETSPLIKTBEHANDLING'
        | 'AVBRYT_REVURDERING'
        | 'AVKLAR_MIGRERINGSDATO'
        | 'AVKLAR_OPPFØLGING'
        | 'AVKLAR_STUDENT'
        | 'AVKLAR_STUDENT_V2'
        | 'AVKLAR_STØNADSPERIODE'
        | 'AVKLAR_SYKDOM'
        | 'BARNETILLEGG'
        | 'BEHANDLENDE_ENHET'
        | 'BEKREFT_VURDERINGER_OPPFØLGING'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'BREV'
        | 'DU_ER_ET_ANNET_STED'
        | 'EFFEKTUER_11_7'
        | 'ETABLERING_EGEN_VIRKSOMHET'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_BEREGNINGSTIDSPUNKT'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_MELDEPERIODER'
        | 'FASTSETT_RETTIGHETSTYPE'
        | 'FASTSETT_SYKDOMSVILKÅRET'
        | 'FASTSETT_UTTAK'
        | 'FASTSETT_VEDTAKSLENGDE'
        | 'FATTE_VEDTAK'
        | 'FORESLÅ_VEDTAK'
        | 'FORESLÅ_VEDTAK_VEDTAKSLENGDE'
        | 'FORMKRAV'
        | 'FRITAK_MELDEPLIKT'
        | 'FULLMEKTIG'
        | 'IKKE_OPPFYLT_MELDEPLIKT'
        | 'IVERKSETT_BRUDD'
        | 'IVERKSETT_KONSEKVENS'
        | 'IVERKSETT_VEDTAK'
        | 'KLAGEBEHANDLING_KONTOR'
        | 'KLAGEBEHANDLING_NAY'
        | 'KLAGEBEHANDLING_OPPSUMMERING'
        | 'KRAV'
        | 'KVALITETSSIKRING'
        | 'MANGLENDE_LIGNING'
        | 'OMGJØRING'
        | 'OPPRETTHOLDELSE'
        | 'OPPRETT_REVURDERING'
        | 'OVERGANG_ARBEID'
        | 'OVERGANG_UFORE'
        | 'PÅKLAGET_BEHANDLING'
        | 'REFUSJON_KRAV'
        | 'SAMORDNING_ANDRE_STATLIGE_YTELSER'
        | 'SAMORDNING_ARBEIDSGIVER'
        | 'SAMORDNING_AVSLAG'
        | 'SAMORDNING_BARNEPENSJON'
        | 'SAMORDNING_GRADERING'
        | 'SAMORDNING_SYKESTIPEND'
        | 'SAMORDNING_TJENESTEPENSJON_REFUSJONSKRAV'
        | 'SAMORDNING_UFØRE'
        | 'SEND_FORVALTNINGSMELDING'
        | 'SIMULERING'
        | 'START_BEHANDLING'
        | 'START_OPPFØLGINGSBEHANDLING'
        | 'SVAR_FRA_ANDREINSTANS'
        | 'SYKDOMSVURDERING_BREV'
        | 'SØKNAD'
        | 'TREKK_KLAGE'
        | 'UDEFINERT'
        | 'VIS_GRUNNLAG'
        | 'VURDER_AKTIVITETSPLIKT_11_7'
        | 'VURDER_AKTIVITETSPLIKT_11_9'
        | 'VURDER_ALDER'
        | 'VURDER_AVSLAG_11_27'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_INNTEKTSBORTFALL'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'VURDER_OPPHOLDSKRAV'
        | 'VURDER_RETTIGHETSPERIODE'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'VURDER_YRKESSKADE'
        | null;
      avklaringsbehov: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvklaringsbehovHendelseDto'][];
      /** @enum {string|null} */
      behandlingMetadata?: 'AVSLAG_11_5_FØRSTEGANGSBEHANDLING' | null;
      /** @enum {string} */
      behandlingType:
        | 'Aktivitetsplikt'
        | 'Aktivitetsplikt11_9'
        | 'Førstegangsbehandling'
        | 'Klage'
        | 'OppfølgingsBehandling'
        | 'Revurdering'
        | 'SvarFraAndreinstans'
        | 'Tilbakekreving';
      'erP\u00E5Vent': boolean;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      hendelsesTidspunkt: string;
      mottattDokumenter: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.MottattDokumentDto'][];
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt: string;
      personIdent: string;
      referanse: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.behandling.BehandlingReferanse'];
      'relevanteIdenterP\u00E5Behandling'?: string[] | null;
      reserverTil?: string | null;
      saksnummer: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.sak.Saksnummer'];
      /** @enum {string} */
      status: 'AVSLUTTET' | 'IVERKSETTES' | 'OPPRETTET' | 'UTREDES';
      versjon: string;
      vurderingsbehov: string[];
      /** @enum {string} */
      '\u00E5rsakTilOpprettelse':
        | 'AKTIVITETSMELDING'
        | 'AKTIVITETSPLIKT'
        | 'AKTIVITETSPLIKT_11_9'
        | 'ANNET_RELEVANT_DOKUMENT'
        | 'BARNETILLEGG_SATSENDRING'
        | 'ENDRING_I_REGISTERDATA'
        | 'FAGSYSTEMINFO_BEHOV_HENDELSE'
        | 'FASTSATT_PERIODE_PASSERT'
        | 'FRITAK_MELDEPLIKT'
        | 'G_REGULERING'
        | 'HELSEOPPLYSNINGER'
        | 'KLAGE'
        | 'MANUELL_OPPRETTELSE'
        | 'MELDEKORT'
        | 'MIGRERING_FRA_ARENA'
        | 'MIGRER_RETTIGHETSPERIODE'
        | 'OMGJØRING_ETTER_KLAGE'
        | 'OMGJØRING_ETTER_SVAR_FRA_KLAGEINSTANS'
        | 'OPPFØLGINGSOPPGAVE'
        | 'OPPFØLGINGSOPPGAVE_SAMORDNING_GRADERING'
        | 'SVAR_FRA_KLAGEINSTANS'
        | 'SØKNAD'
        | 'TILBAKEKREVING_HENDELSE'
        | 'UDEFINERT'
        | 'UFØRE_VEDTAK_HENDELSE'
        | 'UTVID_VEDTAKSLENGDE';
      /**
       * @deprecated
       * @description Kan fjernes når oppgave har byttet til å bruke vurderingsbehov
       */
      '\u00E5rsakerTilBehandling': string[];
    };
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.EndringDTO': {
      begrunnelse?: string | null;
      endretAv: string;
      /**
       * Format: date
       * @example 2025-04-01
       */
      frist?: string | null;
      /** @enum {string} */
      status:
        | 'AVBRUTT'
        | 'AVSLUTTET'
        | 'KVALITETSSIKRET'
        | 'OPPRETTET'
        | 'SENDT_TILBAKE_FRA_BESLUTTER'
        | 'SENDT_TILBAKE_FRA_KVALITETSSIKRER'
        | 'TOTRINNS_VURDERT';
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      tidsstempel: string;
      '\u00E5rsakTilRetur': components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.\u00C5rsakTilRetur'][];
      /** @enum {string|null} */
      '\u00E5rsakTilSattP\u00E5Vent'?:
        | 'VENTER_PÅ_FUNKSJONALITET'
        | 'VENTER_PÅ_FUNKSJONALITET_AVSLAG_11_27'
        | 'VENTER_PÅ_KLAGE_IMPLEMENTASJON'
        | 'VENTER_PÅ_MASKINELL_AVKLARING'
        | 'VENTER_PÅ_MEDISINSKE_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER'
        | 'VENTER_PÅ_SVAR_FRA_BRUKER'
        | 'VENTER_PÅ_SVAR_PÅ_FORHÅNDSVARSEL'
        | 'VENTER_PÅ_UTENLANDSK_VIDEREFORING_AVKLARING'
        | 'VENTER_PÅ_VURDERING_AV_ROL'
        | null;
    };
    /** Format: uuid */
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.InnsendingId': string;
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.InnsendingReferanse': {
      'asAvvistLegeerkl\u00E6ringId': components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.AvvistLegeerkl\u00E6ringId'];
      asInnsendingId: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.InnsendingId'];
      asJournalpostId: components['schemas']['no.nav.aap.verdityper.dokument.JournalpostId'];
      asKabalHendelseId: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.KabalHendelseId'];
      /** @enum {string} */
      type:
        | 'AVVIST_LEGEERKLÆRING_ID'
        | 'BEHANDLING_REFERANSE'
        | 'BRUDD_AKTIVITETSPLIKT_INNSENDING_ID'
        | 'FAGSYSTEMINFO_BEHOV_HENDELSE_ID'
        | 'FORELDREPENGEVEDTAK_HENDELSE_ID'
        | 'INSTITUSJONSOPPHOLD_HENDELSE_ID'
        | 'JOURNALPOST'
        | 'KABAL_HENDELSE_ID'
        | 'MANUELL_OPPRETTELSE'
        | 'MIGRERING_FRA_ARENA'
        | 'PDL_HENDELSE_ID'
        | 'REVURDERING_ID'
        | 'SAKSBEHANDLER_KELVIN_REFERANSE'
        | 'SYKEPENGEVEDTAK_HENDELSE_ID'
        | 'TILBAKEKREVING_HENDELSE_ID'
        | 'UFØREVEDTAK_HENDELSE_ID';
      verdi: string;
    };
    /** Format: uuid */
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.KabalHendelseId': string;
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.MottattDokumentDto': {
      referanse: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.hendelse.InnsendingReferanse'];
      /** @enum {string} */
      type:
        | 'AKTIVITETSKORT'
        | 'ANNET_RELEVANT_DOKUMENT'
        | 'DIALOGMELDING'
        | 'FAGSYSTEMINFO_BEHOV_HENDELSE'
        | 'FORELDREPENGE_VEDTAK_HENDELSE'
        | 'INSTITUSJONSOPPHOLD'
        | 'KABAL_HENDELSE'
        | 'KLAGE'
        | 'LEGEERKLÆRING'
        | 'LEGEERKLÆRING_AVVIST'
        | 'MANUELL_REVURDERING'
        | 'MELDEKORT'
        | 'MIGRERING_FRA_ARENA'
        | 'NY_ÅRSAK_TIL_BEHANDLING'
        | 'OMGJØRING_KLAGE_REVURDERING'
        | 'OPPFØLGINGSOPPGAVE'
        | 'PDL_HENDELSE_DODSFALL_BARN'
        | 'PDL_HENDELSE_DODSFALL_BRUKER'
        | 'PDL_HENDELSE_FOLKEREGISTERIDENT'
        | 'SYKEPENGE_VEDTAK_HENDELSE'
        | 'SØKNAD'
        | 'TILBAKEKREVING_HENDELSE'
        | 'UFØRE_VEDTAK_HENDELSE';
    };
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.TilbakekrevingsbehandlingOppdatertHendelse': {
      /** @enum {string} */
      behandlingStatus:
        | 'AVSLUTTET'
        | 'OPPRETTET'
        | 'RETUR_FRA_BESLUTTER'
        | 'TIL_BEHANDLING'
        | 'TIL_BESLUTTER'
        | 'TIL_FORHÅNDSVARSEL'
        | 'TIL_GODKJENNING';
      behandlingref: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.behandling.BehandlingReferanse'];
      /**
       * Format: date
       * @example 2025-04-01
       */
      gjenopptas?: string | null;
      personIdent: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      sakOpprettet: string;
      saksbehandlingURL: string;
      saksnummer: components['schemas']['no.nav.aap.behandlingsflyt.kontrakt.sak.Saksnummer'];
      'totaltFeilutbetaltBel\u00F8p': number;
      /** @enum {string|null} */
      venteGrunn?: 'AVVENTER_BRUKERUTTALELSE' | null;
    };
    'no.nav.aap.behandlingsflyt.kontrakt.hendelse.\u00C5rsakTilRetur': {
      /** @enum {string} */
      '\u00E5rsak':
        | 'ANNET'
        | 'FEIL_LOVANVENDELSE'
        | 'FOR_DETALJERT'
        | 'IKKE_INDIVIDUELL_OG_KONKRET'
        | 'MANGELFULL_BEGRUNNELSE'
        | 'MANGLENDE_JOURNALFØRING'
        | 'MANGLENDE_KILDEHENVISNING'
        | 'MANGLENDE_UTREDNING'
        | 'SKRIVEFEIL';
    };
    'no.nav.aap.behandlingsflyt.kontrakt.sak.Saksnummer': Record<string, never>;
    'no.nav.aap.motor.JobbTilleggsinfo': {
      kommentarer: components['schemas']['no.nav.aap.motor.Kommentar'][];
    };
    'no.nav.aap.motor.Kommentar': {
      skrevetAv: string;
      tekst: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      tidspunkt: string;
    };
    'no.nav.aap.motor.api.JobbInfoDto': {
      /** Format: int32 */
      'antallFeilendeFors\u00F8k': number;
      beskrivelse: string;
      feilmelding?: string | null;
      /** Format: int64 */
      id: number;
      /** @description Key type: kotlin.String */
      metadata: {
        [key: string]: string;
      };
      navn: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt?: string | null;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      'planlagtKj\u00F8retidspunkt': string;
      /** @enum {string} */
      status: 'AVBRUTT' | 'FEILET' | 'FERDIG' | 'KLAR' | 'PLUKKET';
      tilleggsinfo?: components['schemas']['no.nav.aap.motor.JobbTilleggsinfo'];
      type: string;
    };
    'no.nav.aap.motor.api.`MotorApiKt$motorApi$1$5$LeggTilKommentarRequest`': {
      kommentar: string;
    };
    'no.nav.aap.motor.api.`MotorApiKt$motorApi$1$7$AvbrytJobbRequest`': {
      begrunnelse: string;
    };
    'no.nav.aap.oppgave.BehandlingskontekstResponse': {
      /** Format: uuid */
      behandlingsreferanse: string;
      /** @enum {string} */
      behandlingstype:
        | 'AKTIVITETSPLIKT'
        | 'AKTIVITETSPLIKT_11_9'
        | 'DOKUMENT_HÅNDTERING'
        | 'FORDELING'
        | 'FØRSTEGANGSBEHANDLING'
        | 'JOURNALFØRING'
        | 'KLAGE'
        | 'OPPFØLGINGSBEHANDLING'
        | 'REVURDERING'
        | 'SVAR_FRA_ANDREINSTANS'
        | 'TILBAKEKREVING';
      /** Format: int64 */
      journalpostId?: number | null;
      saksnummer?: string | null;
      tilbakekrevingUrl?: string | null;
    };
    'no.nav.aap.oppgave.ForrigeKvalitetssikrerDto': {
      forrigeKvalitetssikrerIdent: string;
      forrigeKvalitetssikrerNavn?: string | null;
    };
    'no.nav.aap.oppgave.OppgaveId': {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      versjon: number;
    };
    'no.nav.aap.oppgave.ReturInformasjonDto': {
      begrunnelse: string;
      endretAv: string;
      /** @enum {string} */
      status: 'RETUR_FRA_BESLUTTER' | 'RETUR_FRA_KVALITETSSIKRER' | 'RETUR_FRA_SAKSBEHANDLER' | 'RETUR_FRA_VEILEDER';
      '\u00E5rsaker': (
        | 'ANNET'
        | 'FEIL_LOVANVENDELSE'
        | 'FOR_DETALJERT'
        | 'IKKE_INDIVIDUELL_OG_KONKRET'
        | 'MANGELFULL_BEGRUNNELSE'
        | 'MANGLENDE_JOURNALFØRING'
        | 'MANGLENDE_KILDEHENVISNING'
        | 'MANGLENDE_UTREDNING'
        | 'SKRIVEFEIL'
      )[];
    };
    'no.nav.aap.oppgave.SakOgAvklaringsbehov': {
      avklaringsbehovKode: string;
      saksnummer: string;
    };
    'no.nav.aap.oppgave.TilbakekrevingsVarsDto': {
      tilbakekrevings_URL: string;
      'tilbakekrevings_bel\u00F8p': number;
    };
    'no.nav.aap.oppgave.drift.AvklaringsbehovDto': {
      kode: string;
      navn: string;
    };
    'no.nav.aap.oppgave.drift.DriftFilterResponsDTO': {
      avklaringsbehovUtenFilter: components['schemas']['no.nav.aap.oppgave.drift.AvklaringsbehovDto'][];
      filtre: components['schemas']['no.nav.aap.oppgave.drift.FilterDriftResponse'][];
    };
    'no.nav.aap.oppgave.drift.EnhetDriftRequest': {
      enhet: string;
      /** @enum {string} */
      filtermodus: 'EKSKLUDER' | 'INKLUDER';
    };
    'no.nav.aap.oppgave.drift.FilterDriftRequest': {
      avklaringsbehovKoder: string[];
      behandlingstyper: (
        | 'AKTIVITETSPLIKT'
        | 'AKTIVITETSPLIKT_11_9'
        | 'DOKUMENT_HÅNDTERING'
        | 'FORDELING'
        | 'FØRSTEGANGSBEHANDLING'
        | 'JOURNALFØRING'
        | 'KLAGE'
        | 'OPPFØLGINGSBEHANDLING'
        | 'REVURDERING'
        | 'SVAR_FRA_ANDREINSTANS'
        | 'TILBAKEKREVING'
      )[];
      beskrivelse: string;
      enheter: components['schemas']['no.nav.aap.oppgave.drift.EnhetDriftRequest'][];
      /** Format: int64 */
      id?: number | null;
      markeringer: components['schemas']['no.nav.aap.oppgave.drift.MarkeringDriftRequest'][];
      navn: string;
      /** @enum {string} */
      type: 'ALLE_OPPGAVER' | 'GENERELL' | 'KVALITETSSIKRING';
    };
    'no.nav.aap.oppgave.drift.FilterDriftResponse': {
      avklaringsbehov: components['schemas']['no.nav.aap.oppgave.drift.AvklaringsbehovDto'][];
      behandlingstyper: (
        | 'AKTIVITETSPLIKT'
        | 'AKTIVITETSPLIKT_11_9'
        | 'DOKUMENT_HÅNDTERING'
        | 'FORDELING'
        | 'FØRSTEGANGSBEHANDLING'
        | 'JOURNALFØRING'
        | 'KLAGE'
        | 'OPPFØLGINGSBEHANDLING'
        | 'REVURDERING'
        | 'SVAR_FRA_ANDREINSTANS'
        | 'TILBAKEKREVING'
      )[];
      beskrivelse: string;
      ekskluderteEnheter: string[];
      ekskluderteMarkeringer: ('AVSLAG_11_5' | 'HASTER')[];
      endretAv?: string | null;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      endretTidspunkt?: string | null;
      /** Format: int64 */
      id: number;
      inkluderteEnheter: string[];
      inkluderteMarkeringer: ('AVSLAG_11_5' | 'HASTER')[];
      navn: string;
      opprettetAv: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt: string;
      /** @enum {string} */
      type: 'ALLE_OPPGAVER' | 'GENERELL' | 'KVALITETSSIKRING';
    };
    'no.nav.aap.oppgave.drift.MarkeringDriftRequest': {
      /** @enum {string} */
      filtermodus: 'EKSKLUDER' | 'INKLUDER';
      /** @enum {string} */
      type: 'AVSLAG_11_5' | 'HASTER';
    };
    'no.nav.aap.oppgave.drift.OppgaveDriftsinfoDTO': {
      avklaringsbehovKode: string;
      /** Format: uuid */
      behandlingRef: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      endretTidspunkt?: string | null;
      enhet: string;
      historikk: components['schemas']['no.nav.aap.oppgave.drift.OppgaveHistorikkDto'][];
      'oppf\u00F8lgingsenhet'?: string | null;
      /** Format: int64 */
      oppgaveId: number;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt: string;
      reservertAv?: string | null;
      /** @enum {string} */
      status: 'AVSLUTTET' | 'OPPRETTET';
      veilederArbeid?: string | null;
      veilederSykdom?: string | null;
    };
    'no.nav.aap.oppgave.drift.OppgaveHistorikkDto': {
      endretAv?: string | null;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      endretTidspunkt?: string | null;
      enhet: string;
      'oppf\u00F8lgingsenhet'?: string | null;
      reservertAv?: string | null;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      reservertTidspunkt?: string | null;
      /** @enum {string} */
      status: 'AVSLUTTET' | 'OPPRETTET';
    };
    'no.nav.aap.oppgave.drift.SlettFilterRequest': {
      /** Format: int64 */
      id: number;
    };
    'no.nav.aap.oppgave.enhet.EnhetDto': {
      enhetNr: string;
      navn: string;
    };
    'no.nav.aap.oppgave.enhet.EnhetForPersonRequest': {
      personIdent: string;
      relevanteIdenter: string[];
    };
    'no.nav.aap.oppgave.enhet.EnhetNrDto': {
      enhetNr: string;
    };
    'no.nav.aap.oppgave.enhet.EnhetOgOversendelse': {
      tilstand?: components['schemas']['no.nav.aap.oppgave.enhet.N\u00E5v\u00E6rendeEnhet'];
    };
    'no.nav.aap.oppgave.enhet.EnhetSynkroniseringRequest': {
      /** Format: int64 */
      oppgaveId: number;
    };
    'no.nav.aap.oppgave.enhet.EnhetSynkroniseringRespons': {
      gammelEnhet: string;
      nyEnhet: string;
    };
    'no.nav.aap.oppgave.enhet.N\u00E5v\u00E6rendeEnhet': {
      enhet: string;
      markertSomHasteSak: boolean;
      /** @enum {string} */
      oppgaveKategori: 'BESLUTTER' | 'KVALITETSSIKRING' | 'LOKALKONTOR' | 'MEDLEMSKAP' | 'NAY' | 'STUDENT';
      /**
       * Format: date
       * @example 2025-04-01
       */
      oversendtDato: string;
      saksnummer: string;
      'vente\u00C5rsak'?: string | null;
    };
    'no.nav.aap.oppgave.enhet.OppgaveEnhetDto': {
      avklaringsbehovKode: string;
      enhet: string;
    };
    'no.nav.aap.oppgave.enhet.OppgaveEnhetResponse': {
      oppgaver: components['schemas']['no.nav.aap.oppgave.enhet.OppgaveEnhetDto'][];
    };
    'no.nav.aap.oppgave.enhet.PersonRequest': {
      ident: string;
    };
    'no.nav.aap.oppgave.filter.FilterResponse': {
      beskrivelse: string;
      /** Format: int64 */
      id: number;
      inneholderTilbakekreving: boolean;
      navn: string;
      /** @enum {string} */
      type: 'ALLE_OPPGAVER' | 'GENERELL' | 'KVALITETSSIKRING';
    };
    'no.nav.aap.oppgave.hent.OppgaveP\u00E5BehandlingResponse': {
      /** Format: uuid */
      behandlingsreferanse: string;
      /** Format: int64 */
      id: number;
      reservertAvIdent?: string | null;
      reservertAvNavn?: string | null;
      /** Format: int64 */
      versjon: number;
    };
    'no.nav.aap.oppgave.hent.OppgaveVisningsinformasjonResponse': {
      harUlesteDokumenter: boolean;
      /** Format: int64 */
      id: number;
      markeringer: components['schemas']['no.nav.aap.oppgave.markering.MarkeringDto'][];
      'p\u00E5VentInfo'?: components['schemas']['no.nav.aap.oppgave.hent.VenteInformasjonResponse'];
      reservertAvIdent?: string | null;
      reservertAvNavn?: string | null;
      returInformasjon?: components['schemas']['no.nav.aap.oppgave.ReturInformasjonDto'];
      saksnummer?: string | null;
      skjermingInfo: components['schemas']['no.nav.aap.oppgave.hent.SkjermingInfoResponse'];
      'utl\u00F8ptVenteInfo'?: components['schemas']['no.nav.aap.oppgave.hent.VenteInformasjonResponse'];
      /** Format: int64 */
      versjon: number;
    };
    'no.nav.aap.oppgave.hent.OppgaverP\u00E5SakResponse': {
      oppgaver: components['schemas']['no.nav.aap.oppgave.hent.OppgaveP\u00E5BehandlingResponse'][];
    };
    'no.nav.aap.oppgave.hent.SaksnummerResponse': {
      saksnummer: string;
    };
    'no.nav.aap.oppgave.hent.SkjermingInfoResponse': {
      erSkjermet: boolean;
      harFortroligAdresse: boolean;
      harStrengtFortroligAdresse: boolean;
    };
    'no.nav.aap.oppgave.hent.VenteInformasjonResponse': {
      /**
       * Format: date
       * @example 2025-04-01
       */
      'p\u00E5VentTil': string;
      'p\u00E5Vent\u00C5rsak'?: string | null;
      venteBegrunnelse?: string | null;
    };
    'no.nav.aap.oppgave.liste.OppgaveMedKontekstResponse': {
      avklaringsbehovKode: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      behandlingOpprettet: string;
      behandlingskontekst: components['schemas']['no.nav.aap.oppgave.BehandlingskontekstResponse'];
      oppgaveMetadata: components['schemas']['no.nav.aap.oppgave.liste.OppgaveMetadataResponse'];
      oppgavelisteTags: components['schemas']['no.nav.aap.oppgave.liste.OppgavelisteTagsResponse'];
      personOgEnhet: components['schemas']['no.nav.aap.oppgave.liste.PersonOgEnhetResponse'];
      reservertAv?: string | null;
      reservertAvNavn?: string | null;
      tilbakekrevingsVars?: components['schemas']['no.nav.aap.oppgave.TilbakekrevingsVarsDto'];
      veilederArbeid?: string | null;
      veilederSykdom?: string | null;
      vurderingsbehov: string[];
      '\u00E5rsakTilOpprettelse'?: string | null;
    };
    'no.nav.aap.oppgave.liste.OppgaveMetadataResponse': {
      /** Format: int64 */
      id: number;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt: string;
      /** @enum {string} */
      status: 'AVSLUTTET' | 'OPPRETTET';
      /** Format: int64 */
      versjon: number;
    };
    'no.nav.aap.oppgave.liste.OppgaveSortering': {
      /** @enum {string|null} */
      sortBy?:
        | 'AVKLARINGSBEHOV_KODE'
        | 'BEHANDLINGSTYPE'
        | 'BEHANDLING_OPPRETTET'
        | 'OPPRETTET_TIDSPUNKT'
        | 'PERSONIDENT'
        | 'RESERVERT_AV'
        | 'SAKSNUMMER'
        | 'TILBAKEKREVINGS_BELOP'
        | 'ÅRSAK_TIL_OPPRETTELSE'
        | null;
      /** @enum {string|null} */
      sortOrder?: 'ASC' | 'DESC' | null;
    };
    'no.nav.aap.oppgave.liste.OppgavelisteRequest': {
      enheter: string[];
      /** Format: int64 */
      filterId: number;
      'hastemarkeringerF\u00F8rst'?: boolean | null;
      kunLedigeOppgaver?: boolean | null;
      paging: components['schemas']['no.nav.aap.oppgave.liste.Paging'];
      sortering?: components['schemas']['no.nav.aap.oppgave.liste.OppgaveSortering'];
      utvidetFilter?: components['schemas']['no.nav.aap.oppgave.liste.UtvidetOppgavelisteFilter'];
      veileder: boolean;
    };
    'no.nav.aap.oppgave.liste.OppgavelisteRespons': {
      /** Format: int32 */
      antallGjenstaaende?: number | null;
      /** Format: int32 */
      antallTotalt: number;
      oppgaver: components['schemas']['no.nav.aap.oppgave.liste.OppgaveMedKontekstResponse'][];
      sattFilterBehandlingstyper?:
        | (
            | 'AKTIVITETSPLIKT'
            | 'AKTIVITETSPLIKT_11_9'
            | 'DOKUMENT_HÅNDTERING'
            | 'FORDELING'
            | 'FØRSTEGANGSBEHANDLING'
            | 'JOURNALFØRING'
            | 'KLAGE'
            | 'OPPFØLGINGSBEHANDLING'
            | 'REVURDERING'
            | 'SVAR_FRA_ANDREINSTANS'
            | 'TILBAKEKREVING'
          )[]
        | null;
    };
    'no.nav.aap.oppgave.liste.OppgavelisteTagsResponse': {
      forrigeKvalitetssikrerInfo?: components['schemas']['no.nav.aap.oppgave.ForrigeKvalitetssikrerDto'];
      'forrigeP\u00E5VentInfo'?: components['schemas']['no.nav.aap.oppgave.hent.VenteInformasjonResponse'];
      harUlesteDokumenter?: boolean | null;
      markeringer: components['schemas']['no.nav.aap.oppgave.markering.MarkeringDto'][];
      'p\u00E5VentInfo'?: components['schemas']['no.nav.aap.oppgave.hent.VenteInformasjonResponse'];
      returInformasjon?: components['schemas']['no.nav.aap.oppgave.ReturInformasjonDto'];
      skjermingInfo: components['schemas']['no.nav.aap.oppgave.hent.SkjermingInfoResponse'];
    };
    'no.nav.aap.oppgave.liste.Paging': {
      /** Format: int32 */
      antallPerSide: number;
      /** Format: int32 */
      side: number;
    };
    'no.nav.aap.oppgave.liste.PersonOgEnhetResponse': {
      enhet: string;
      enhetForrigeOppgave?: components['schemas']['no.nav.aap.oppgave.enhet.EnhetDto'];
      'oppf\u00F8lgingsenhet'?: string | null;
      personIdent: string;
      personNavn?: string | null;
    };
    'no.nav.aap.oppgave.liste.UtvidetOppgavelisteFilter': {
      avklaringsbehovKoder: string[];
      behandlingstyper: (
        | 'AKTIVITETSPLIKT'
        | 'AKTIVITETSPLIKT_11_9'
        | 'DOKUMENT_HÅNDTERING'
        | 'FORDELING'
        | 'FØRSTEGANGSBEHANDLING'
        | 'JOURNALFØRING'
        | 'KLAGE'
        | 'OPPFØLGINGSBEHANDLING'
        | 'REVURDERING'
        | 'SVAR_FRA_ANDREINSTANS'
        | 'TILBAKEKREVING'
      )[];
      'bel\u00F8pMerEnn'?: number | null;
      'bel\u00F8pMindreEnn'?: number | null;
      /**
       * Format: date
       * @example 2025-04-01
       */
      fom?: string | null;
      markertHaster?: boolean | null;
      'p\u00E5Vent'?: boolean | null;
      returStatuser: (
        | 'RETUR_FRA_BESLUTTER'
        | 'RETUR_FRA_KVALITETSSIKRER'
        | 'RETUR_FRA_SAKSBEHANDLER'
        | 'RETUR_FRA_VEILEDER'
      )[];
      saksbehandlere: string[];
      /**
       * Format: date
       * @example 2025-04-01
       */
      tom?: string | null;
      'ventefristUtl\u00F8pt'?: boolean | null;
      '\u00E5rsaker': string[];
    };
    'no.nav.aap.oppgave.markering.MarkeringDto': {
      begrunnelse?: string | null;
      /** @enum {string|null} */
      hendelseType?: 'FJERNET' | 'OPPRETTET' | null;
      /** @enum {string} */
      markeringType: 'AVSLAG_11_5' | 'HASTER';
      opprettetAv?: string | null;
      opprettetAvNavn?: string | null;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt?: string | null;
    };
    'no.nav.aap.oppgave.markering.MarkeringOgHistorikk': {
      begrunnelse?: string | null;
      behandlingRef: string;
      /** @enum {string|null} */
      hendelseType?: 'FJERNET' | 'OPPRETTET' | null;
      /** @enum {string} */
      markeringType: 'AVSLAG_11_5' | 'HASTER';
      opprettetAv: string;
      opprettetAvNavn?: string | null;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt: string;
    };
    'no.nav.aap.oppgave.markering.OpprettMarkeringDto': {
      begrunnelse?: string | null;
      /** @enum {string|null} */
      hendelseType?: 'FJERNET' | 'OPPRETTET' | null;
      /** @enum {string} */
      markeringType: 'AVSLAG_11_5' | 'HASTER';
    };
    'no.nav.aap.oppgave.mottattdokument.DokumenterLestDto': {
      /** Format: uuid */
      behandlingRef: string;
    };
    'no.nav.aap.oppgave.plukk.AvreserverOppgaveDto': {
      oppgaver: number[];
    };
    'no.nav.aap.oppgave.plukk.PlukkOppgaveRequest': {
      /** Format: int64 */
      oppgaveId: number;
      /** Format: int64 */
      versjon: number;
    };
    'no.nav.aap.oppgave.plukk.PlukkOppgaveResponse': {
      behandlingskontekst: components['schemas']['no.nav.aap.oppgave.BehandlingskontekstResponse'];
    };
    'no.nav.aap.oppgave.s\u00F8k.OppgaveIS\u00F8kResponse': {
      avklaringsbehovKode: string;
      behandlingskontekst: components['schemas']['no.nav.aap.oppgave.BehandlingskontekstResponse'];
      'enhetForK\u00F8': string;
      'erP\u00E5Vent': boolean;
      personNavn?: string | null;
      reservertAvIdent?: string | null;
      typeMarkeringer: ('AVSLAG_11_5' | 'HASTER')[];
    };
    'no.nav.aap.oppgave.s\u00F8k.S\u00F8kRequest': {
      's\u00F8ketekst': string;
    };
    'no.nav.aap.oppgave.s\u00F8k.S\u00F8kResponse': {
      harAdressebeskyttelse: boolean;
      harTilgang: boolean;
      oppgaver: components['schemas']['no.nav.aap.oppgave.s\u00F8k.OppgaveIS\u00F8kResponse'][];
    };
    'no.nav.aap.oppgave.tildel.SaksbehandlerDto': {
      navIdent: string;
      navn?: string | null;
    };
    'no.nav.aap.oppgave.tildel.SaksbehandlerS\u00F8kRequest': {
      enheter?: string[] | null;
      oppgaver: number[];
      's\u00F8ketekst': string;
    };
    'no.nav.aap.oppgave.tildel.SaksbehandlerS\u00F8kResponse': {
      saksbehandlere: components['schemas']['no.nav.aap.oppgave.tildel.SaksbehandlerDto'][];
    };
    'no.nav.aap.oppgave.tildel.TildelOppgaveRequest': {
      oppgaver: number[];
      saksbehandlerIdent: string;
    };
    'no.nav.aap.oppgave.tildel.TildelOppgaveResponse': {
      oppgaver: number[];
      tildeltTilSaksbehandler: string;
    };
    'no.nav.aap.oppgave.tildel.TildeltStatusDto': {
      erTildeltInnloggetBruker: boolean;
      tildeltSaksbehandlerIdent?: string | null;
      tildeltSaksbehandlerNavn?: string | null;
    };
    'no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon': {
      /** @enum {string} */
      kode: '1337' | '1338' | '1339' | '1340' | '1341' | '1342' | '1343' | '9001';
      kreverToTrinn: boolean;
      'l\u00F8sesAv': (
        | 'BESLUTTER'
        | 'DRIFT'
        | 'KVALITETSSIKRER'
        | 'LES'
        | 'PRODUKSJONSSTYRING'
        | 'SAKSBEHANDLER_NASJONAL'
        | 'SAKSBEHANDLER_OPPFOLGING'
      )[];
      /** @enum {string} */
      'l\u00F8sesISteg':
        | 'AVKLAR_FORDELING'
        | 'AVKLAR_FORDELING_VIDERESEND'
        | 'AVKLAR_SAK'
        | 'AVKLAR_TEMA'
        | 'DIGITALISER_DOKUMENT'
        | 'ENDELIG_JOURNALFØRING'
        | 'IVERKSETTES'
        | 'OVERLEVER_TIL_FAGSYSTEM'
        | 'SETT_FAGSAK'
        | 'START_BEHANDLING'
        | 'UDEFINERT'
        | 'VIDERESEND';
      /** @enum {string} */
      type: 'MANUELT_FRIVILLIG' | 'MANUELT_PÅKREVD' | 'VENTEPUNKT';
      name: string;
    };
    'no.nav.aap.postmottak.kontrakt.hendelse.AvklaringsbehovHendelseDto': {
      avklaringsbehovDefinisjon: components['schemas']['no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon'];
      endringer: components['schemas']['no.nav.aap.postmottak.kontrakt.hendelse.EndringDTO'][];
      /** @enum {string} */
      status: 'AVBRUTT' | 'AVSLUTTET' | 'OPPRETTET' | 'SENDT_TILBAKE_FRA_BESLUTTER';
    };
    'no.nav.aap.postmottak.kontrakt.hendelse.DokumentflytStoppetHendelse': {
      avklaringsbehov: components['schemas']['no.nav.aap.postmottak.kontrakt.hendelse.AvklaringsbehovHendelseDto'][];
      /** @enum {string} */
      behandlingType: 'DokumentHåndtering' | 'Fordeling' | 'Journalføring';
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      hendelsesTidspunkt: string;
      ident: string;
      journalpostId: components['schemas']['no.nav.aap.postmottak.kontrakt.journalpost.JournalpostId'];
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt: string;
      /** Format: uuid */
      referanse: string;
      /** @enum {string} */
      status: 'AVSLUTTET' | 'IVERKSETTES' | 'OPPRETTET' | 'UTREDES';
    };
    'no.nav.aap.postmottak.kontrakt.hendelse.EndringDTO': {
      begrunnelse?: string | null;
      endretAv: string;
      /**
       * Format: date
       * @example 2025-04-01
       */
      frist?: string | null;
      /** @enum {string} */
      status: 'AVBRUTT' | 'AVSLUTTET' | 'OPPRETTET' | 'SENDT_TILBAKE_FRA_BESLUTTER';
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      tidsstempel: string;
      /** @enum {string|null} */
      '\u00E5rsakTilSattP\u00E5Vent'?:
        | 'VENTER_PÅ_BEHANDLING_I_GOSYS'
        | 'VENTER_PÅ_MEDISINSKE_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER'
        | 'VENTER_PÅ_SVAR_FRA_BRUKER'
        | 'VENTER_PÅ_VURDERING_AV_ROL'
        | null;
    };
    /** Format: int64 */
    'no.nav.aap.postmottak.kontrakt.journalpost.JournalpostId': number;
    'no.nav.aap.verdityper.dokument.JournalpostId': {
      identifikator: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
