/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/behandling/{referanse}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.DetaljertBehandlingDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/forbered': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.DetaljertBehandlingDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.JournalpostDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.journalpostogbehandling.behandling.BehandlingsreferansePathParam'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/flyt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.BehandlingFlytOgTilstandDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/resultat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.BehandlingResultatDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/sett-p\u00E5-vent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.SettP\u00E5VentRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.BehandlingResultatDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/vente-informasjon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.Venteinformasjon'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/l\u00F8s-behov': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.L\u00F8sAvklaringsbehovP\u00E5Behandling'];
        };
      };
      responses: {
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.flyt.L\u00F8sAvklaringsbehovP\u00E5Behandling'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dokumenter/{journalpostId}/{dokumentinfoId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Journalpost-ID */
          journalpostId: number;
          /** @description Dokumentinfo-ID */
          dokumentinfoId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/pdf': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dokumenter/{referanse}/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.dokument.DokumentInfoResponsDTO'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dokumenter/finn-ubehandlede': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.joarkavstemmer.UavstemtJournalpost'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/grunnlag/avklarTemaVurdering': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.tema.AvklarTemaGrunnlagDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/grunnlag/finnSak': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.sak.AvklarSakGrunnlagDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/alle-behandlinger': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.sak.IdentRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.sak.FinnBehandlingerResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/grunnlag/digitalisering': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.strukturering.DigitaliseringGrunnlagDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/behandling/{referanse}/grunnlag/overlevering': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.overlevering.OverleveringGrunnlagDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/feilende': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/feilende/antall': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': number;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/planlagte-jobber': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/{jobbId}/kjor': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/{jobbId}/leggTilKommentar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.motor.api.`MotorApiKt$motorApi$1$5$LeggTilKommentarRequest`'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.Kommentar'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/rekjor/{jobbId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/avbryt/{jobbId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID */
          jobbId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.motor.api.`MotorApiKt$motorApi$1$7$AvbrytJobbRequest`'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/avbrytAlleFeilede': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/rekjorAlleFeilede': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/drift/api/jobb/sisteKj\u00F8rte': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/test/hentAlleBehandlinger': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.test.BehandlingsListe'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/test/finnEnhetMedOppfolgingskontor/{ident}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ident */
          ident: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.fordeler.EnhetMedOppf\u00F8lgingsKontor'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/journalpost/{referanse}/auditlog': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/drift/behandling/{referanse}/prosesser': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/drift/journalpost/{referanse}/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description referanse */
          referanse: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['no.nav.aap.postmottak.api.drift.JournalpostDriftsinfoDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/test/simulerJournalpostHendelse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.postmottak.SimulerJournalpostHendelseRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'no.nav.aap.fordeler.EnhetMedOppf\u00F8lgingsKontor': {
      norgEnhet?: string | null;
      'oppf\u00F8lgingsenhet'?: string | null;
    };
    'no.nav.aap.fordeler.Regelresultat': {
      /** Format: int64 */
      forJournalpost: number;
      /** @description Key type: kotlin.String */
      regelMap: {
        [key: string]: boolean;
      };
      systemNavn?: string | null;
    };
    'no.nav.aap.komponenter.type.Periode': {
      /**
       * Format: date
       * @example 2025-04-01
       */
      fom: string;
      /**
       * Format: date
       * @example 2025-04-01
       */
      tom: string;
    };
    'no.nav.aap.motor.JobbTilleggsinfo': {
      kommentarer: components['schemas']['no.nav.aap.motor.Kommentar'][];
    };
    'no.nav.aap.motor.Kommentar': {
      skrevetAv: string;
      tekst: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      tidspunkt: string;
    };
    'no.nav.aap.motor.api.JobbInfoDto': {
      /** Format: int32 */
      'antallFeilendeFors\u00F8k': number;
      beskrivelse: string;
      feilmelding?: string | null;
      /** Format: int64 */
      id: number;
      /** @description Key type: kotlin.String */
      metadata: {
        [key: string]: string;
      };
      navn: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettetTidspunkt?: string | null;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      'planlagtKj\u00F8retidspunkt': string;
      /** Format: int32 */
      prioritet?: number | null;
      /** @enum {string} */
      status: 'AVBRUTT' | 'FEILET' | 'FERDIG' | 'KLAR' | 'PLUKKET';
      tilleggsinfo?: components['schemas']['no.nav.aap.motor.JobbTilleggsinfo'];
      type: string;
    };
    'no.nav.aap.motor.api.`MotorApiKt$motorApi$1$5$LeggTilKommentarRequest`': {
      kommentar: string;
    };
    'no.nav.aap.motor.api.`MotorApiKt$motorApi$1$7$AvbrytJobbRequest`': {
      begrunnelse: string;
    };
    'no.nav.aap.postmottak.SimulerJournalpostHendelseRequest': {
      fnr?: string | null;
      hendelsesType: string;
      /** Format: int64 */
      journalpostId: number;
      journalpostStatus: string;
      /** @enum {string} */
      scenario: 'DIGITAL_SØKNAD' | 'LEGEERKLÆRING' | 'PAPIRSØKNAD' | 'UTENLANDSK_ORGNR';
      tema: string;
      temaGammelt?: string | null;
    };
    'no.nav.aap.postmottak.api.drift.BehandlingDriftsinfo': {
      aktivtSteg: string;
      avklaringsbehov: components['schemas']['no.nav.aap.postmottak.api.drift.ForenkletAvklaringsbehov'][];
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettet: string;
      /** Format: uuid */
      referanse: string;
      /** @enum {string} */
      status: 'AVSLUTTET' | 'IVERKSETTES' | 'OPPRETTET' | 'UTREDES';
      type: string;
    };
    'no.nav.aap.postmottak.api.drift.ForenkletAvklaringsbehov': {
      definisjon: components['schemas']['no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon'];
      endretAv: string;
      /** @enum {string} */
      status: 'AVBRUTT' | 'AVSLUTTET' | 'OPPRETTET' | 'SENDT_TILBAKE_FRA_BESLUTTER';
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      tidsstempel: string;
      /** @enum {string|null} */
      '\u00E5rsakTilSettP\u00E5Vent'?:
        | 'VENTER_PÅ_BEHANDLING_I_GOSYS'
        | 'VENTER_PÅ_MEDISINSKE_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER'
        | 'VENTER_PÅ_SVAR_FRA_BRUKER'
        | 'VENTER_PÅ_VURDERING_AV_ROL'
        | null;
    };
    'no.nav.aap.postmottak.api.drift.JournalpostDriftsinfoDto': {
      behandlinger: components['schemas']['no.nav.aap.postmottak.api.drift.BehandlingDriftsinfo'][];
      brevkode?: string | null;
      fordelingsresultat?: components['schemas']['no.nav.aap.fordeler.Regelresultat'];
      /** @enum {string|null} */
      innkommendeStatus?:
        | 'EVALUERT'
        | 'GOSYS_FDR'
        | 'GOSYS_JFR'
        | 'IGNORERT'
        | 'VIDERESENDT_TIL_ARENA'
        | 'VIDERSENDT_TIL_KELVIN'
        | null;
      /** @enum {string|null} */
      journalstatus?:
        | 'AVBRUTT'
        | 'EKSPEDERT'
        | 'FEILREGISTRERT'
        | 'FERDIGSTILT'
        | 'JOURNALFOERT'
        | 'MOTTATT'
        | 'OPPLASTING_DOKUMENT'
        | 'RESERVERT'
        | 'UKJENT'
        | 'UKJENT_BRUKER'
        | 'UNDER_ARBEID'
        | 'UTGAAR'
        | null;
      /** @enum {string|null} */
      kanal?:
        | 'ALTINN'
        | 'ALTINN_INNBOKS'
        | 'DPVT'
        | 'EESSI'
        | 'EIA'
        | 'EKST_OPPS'
        | 'E_POST'
        | 'HELSENETTET'
        | 'INGEN_DISTRIBUSJON'
        | 'INNSENDT_NAV_ANSATT'
        | 'LOKAL_UTSKRIFT'
        | 'NAV_NO'
        | 'NAV_NO_CHAT'
        | 'NAV_NO_UINNLOGGET'
        | 'SDP'
        | 'SENTRAL_UTSKRIFT'
        | 'SKAN_IM'
        | 'SKAN_NETS'
        | 'SKAN_PEN'
        | 'TRYGDERETTEN'
        | 'UKJENT'
        | null;
      /**
       * Format: date
       * @example 2025-04-01
       */
      mottattDato?: string | null;
      saksnummer?: string | null;
      tema?: string | null;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.dokument.DokumentDto': {
      dokumentInfoId: string;
      tittel?: string | null;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.dokument.DokumentIdent': {
      ident?: string | null;
      navn?: string | null;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.dokument.DokumentInfoResponsDTO': {
      avsender?: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.dokument.DokumentIdent'];
      dokumenter: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.dokument.DokumentDto'][];
      /** Format: int64 */
      journalpostId: number;
      /**
       * Format: date
       * @example 2025-04-01
       */
      registrertDato?: string | null;
      's\u00F8ker'?: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.dokument.DokumentIdent'];
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.overlevering.OverleveringGrunnlagDto': {
      vurdering?: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.overlevering.OverleveringVurderingDto'];
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.overlevering.OverleveringVurderingDto': {
      skalOverleveres: boolean;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.sak.AvklarSakGrunnlagDto': {
      avsenderMottaker?: components['schemas']['no.nav.aap.postmottak.journalpostogbehandling.journalpost.AvsenderMottaker'];
      brevkode: string;
      dokumenter: components['schemas']['no.nav.aap.postmottak.journalpostogbehandling.journalpost.Dokument'][];
      journalposttittel?: string | null;
      kanEndreAvsenderMottaker: boolean;
      kanOppretteNySak: boolean;
      saksinfo: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.sak.SaksInfoDto'][];
      vurdering?: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.sak.AvklarSakVurderingDto'];
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.sak.AvklarSakVurderingDto': {
      'f\u00F8rP\u00E5GenerellSak': boolean;
      saksnummer?: string | null;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.sak.BehandlinginfoDTO': {
      journalPostId: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettet: string;
      /** Format: uuid */
      referanse: string;
      /** @enum {string} */
      status: 'AVSLUTTET' | 'IVERKSETTES' | 'OPPRETTET' | 'UTREDES';
      /** @enum {string} */
      typeBehandling: 'DokumentHåndtering' | 'Fordeling' | 'Journalføring';
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.sak.FinnBehandlingerResponse': {
      behandlinger: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.sak.BehandlinginfoDTO'][];
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.sak.IdentRequest': {
      ident: string;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.sak.SaksInfoDto': {
      periode: components['schemas']['no.nav.aap.komponenter.type.Periode'];
      /** @enum {string|null} */
      resultat?:
        | 'AVBRUTT'
        | 'AVSLAG'
        | 'INNVILGET'
        | 'KLAGE_AVSLÅTT'
        | 'KLAGE_DELVIS_OMGJØRES'
        | 'KLAGE_OMGJØRES'
        | 'KLAGE_OPPRETTHOLDES'
        | 'KLAGE_TRUKKET'
        | 'TRUKKET'
        | null;
      saksnummer: string;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.strukturering.DigitaliseringGrunnlagDto': {
      erPapir: boolean;
      klagebehandlinger: components['schemas']['no.nav.aap.postmottak.gateway.Klagebehandling'][];
      vurdering?: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.strukturering.DigitaliseringvurderingDto'];
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.strukturering.DigitaliseringvurderingDto': {
      /** @enum {string} */
      kategori:
        | 'AKTIVITETSKORT'
        | 'ANNET_RELEVANT_DOKUMENT'
        | 'DIALOGMELDING'
        | 'FAGSYSTEMINFO_BEHOV_HENDELSE'
        | 'FORELDREPENGE_VEDTAK_HENDELSE'
        | 'INSTITUSJONSOPPHOLD'
        | 'KABAL_HENDELSE'
        | 'KLAGE'
        | 'LEGEERKLÆRING'
        | 'LEGEERKLÆRING_AVVIST'
        | 'MANUELL_REVURDERING'
        | 'MELDEKORT'
        | 'MIGRERING_FRA_ARENA'
        | 'NY_ÅRSAK_TIL_BEHANDLING'
        | 'OMGJØRING_KLAGE_REVURDERING'
        | 'OPPFØLGINGSOPPGAVE'
        | 'PDL_HENDELSE_DODSFALL_BARN'
        | 'PDL_HENDELSE_DODSFALL_BRUKER'
        | 'PDL_HENDELSE_FOLKEREGISTERIDENT'
        | 'SYKEPENGE_VEDTAK_HENDELSE'
        | 'SØKNAD'
        | 'TILBAKEKREVING_HENDELSE'
        | 'UFØRE_VEDTAK_HENDELSE';
      strukturertDokumentJson?: string | null;
      /**
       * Format: date
       * @example 2025-04-01
       */
      's\u00F8knadsdato'?: string | null;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.tema.AvklarTemaGrunnlagDto': {
      dokumenter: string[];
      journalpostMetadata: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.tema.JournalpostMetadata'];
      vurdering?: components['schemas']['no.nav.aap.postmottak.api.faktagrunnlag.tema.AvklarTemaVurderingDto'];
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.tema.AvklarTemaVurderingDto': {
      skalTilAap: boolean;
    };
    'no.nav.aap.postmottak.api.faktagrunnlag.tema.JournalpostMetadata': {
      brevkode?: string | null;
      journalfoerendeEnhet?: string | null;
    };
    'no.nav.aap.postmottak.api.flyt.AvklaringsbehovDTO': {
      definisjon: components['schemas']['no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon'];
      endringer: components['schemas']['no.nav.aap.postmottak.api.flyt.EndringDTO'][];
      /** @enum {string} */
      status: 'AVBRUTT' | 'AVSLUTTET' | 'OPPRETTET' | 'SENDT_TILBAKE_FRA_BESLUTTER';
    };
    'no.nav.aap.postmottak.api.flyt.BehandlingFlytOgTilstandDto': {
      /** @enum {string} */
      aktivGruppe:
        | 'AVKLAR_FORDELING'
        | 'AVKLAR_SAK'
        | 'AVKLAR_TEMA'
        | 'DIGITALISER'
        | 'ENDELIG_JOURNALFØRING'
        | 'IVERKSETTES'
        | 'KATEGORISER'
        | 'OVERLEVER_TIL_FAGSYSTEM'
        | 'SETT_FAGSAK'
        | 'START_BEHANDLING'
        | 'UDEFINERT'
        | 'VIDERESEND';
      /** @enum {string} */
      aktivtSteg:
        | 'AVKLAR_FORDELING'
        | 'AVKLAR_FORDELING_VIDERESEND'
        | 'AVKLAR_SAK'
        | 'AVKLAR_TEMA'
        | 'DIGITALISER_DOKUMENT'
        | 'ENDELIG_JOURNALFØRING'
        | 'IVERKSETTES'
        | 'OVERLEVER_TIL_FAGSYSTEM'
        | 'SETT_FAGSAK'
        | 'START_BEHANDLING'
        | 'UDEFINERT'
        | 'VIDERESEND';
      /** Format: int64 */
      behandlingVersjon: number;
      flyt: components['schemas']['no.nav.aap.postmottak.api.flyt.FlytGruppe'][];
      /** Format: uuid */
      nesteBehandlingId?: string | null;
      prosessering: components['schemas']['no.nav.aap.postmottak.api.flyt.Prosessering'];
      visning: components['schemas']['no.nav.aap.postmottak.flyt.flate.visning.Visning'];
    };
    'no.nav.aap.postmottak.api.flyt.BehandlingResultatDto': Record<string, never>;
    'no.nav.aap.postmottak.api.flyt.DetaljertBehandlingDto': {
      /** @enum {string} */
      aktivtSteg:
        | 'AVKLAR_FORDELING'
        | 'AVKLAR_FORDELING_VIDERESEND'
        | 'AVKLAR_SAK'
        | 'AVKLAR_TEMA'
        | 'DIGITALISER_DOKUMENT'
        | 'ENDELIG_JOURNALFØRING'
        | 'IVERKSETTES'
        | 'OVERLEVER_TIL_FAGSYSTEM'
        | 'SETT_FAGSAK'
        | 'START_BEHANDLING'
        | 'UDEFINERT'
        | 'VIDERESEND';
      avklaringsbehov: components['schemas']['no.nav.aap.postmottak.api.flyt.AvklaringsbehovDTO'][];
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettet: string;
      referanse: components['schemas']['no.nav.aap.postmottak.journalpostogbehandling.behandling.BehandlingsreferansePathParam'];
      skalForberede: boolean;
      /** @enum {string} */
      status: 'AVSLUTTET' | 'IVERKSETTES' | 'OPPRETTET' | 'UTREDES';
      type: string;
      /** Format: int64 */
      versjon: number;
    };
    'no.nav.aap.postmottak.api.flyt.EndringDTO': {
      begrunnelse?: string | null;
      endretAv: string;
      /** @enum {string} */
      status: 'AVBRUTT' | 'AVSLUTTET' | 'OPPRETTET' | 'SENDT_TILBAKE_FRA_BESLUTTER';
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      tidsstempel: string;
    };
    'no.nav.aap.postmottak.api.flyt.FlytGruppe': {
      'erFullf\u00F8rt': boolean;
      skalVises: boolean;
      steg: components['schemas']['no.nav.aap.postmottak.api.flyt.FlytSteg'][];
      /** @enum {string} */
      stegGruppe:
        | 'AVKLAR_FORDELING'
        | 'AVKLAR_SAK'
        | 'AVKLAR_TEMA'
        | 'DIGITALISER'
        | 'ENDELIG_JOURNALFØRING'
        | 'IVERKSETTES'
        | 'KATEGORISER'
        | 'OVERLEVER_TIL_FAGSYSTEM'
        | 'SETT_FAGSAK'
        | 'START_BEHANDLING'
        | 'UDEFINERT'
        | 'VIDERESEND';
    };
    'no.nav.aap.postmottak.api.flyt.FlytSteg': {
      avklaringsbehov: components['schemas']['no.nav.aap.postmottak.api.flyt.AvklaringsbehovDTO'][];
      /** @enum {string} */
      stegType:
        | 'AVKLAR_FORDELING'
        | 'AVKLAR_FORDELING_VIDERESEND'
        | 'AVKLAR_SAK'
        | 'AVKLAR_TEMA'
        | 'DIGITALISER_DOKUMENT'
        | 'ENDELIG_JOURNALFØRING'
        | 'IVERKSETTES'
        | 'OVERLEVER_TIL_FAGSYSTEM'
        | 'SETT_FAGSAK'
        | 'START_BEHANDLING'
        | 'UDEFINERT'
        | 'VIDERESEND';
    };
    'no.nav.aap.postmottak.api.flyt.JournalpostDto': {
      /** Format: int64 */
      referanse: number;
    };
    'no.nav.aap.postmottak.api.flyt.L\u00F8sAvklaringsbehovP\u00E5Behandling': {
      /** Format: int64 */
      behandlingVersjon: number;
      behov: components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklaringsbehovL\u00F8sning'];
      ingenEndringIGruppe?: boolean | null;
      referanse: components['schemas']['no.nav.aap.postmottak.journalpostogbehandling.behandling.Behandlingsreferanse'];
    };
    'no.nav.aap.postmottak.api.flyt.Prosessering': {
      /** @enum {string} */
      status: 'FEILET' | 'FERDIG' | 'JOBBER';
      ventendeOppgaver: components['schemas']['no.nav.aap.motor.api.JobbInfoDto'][];
    };
    'no.nav.aap.postmottak.api.flyt.SettP\u00E5VentRequest': {
      begrunnelse: string;
      /** Format: int64 */
      behandlingVersjon: number;
      /**
       * Format: date
       * @example 2025-04-01
       */
      frist?: string | null;
      /** @enum {string} */
      grunn:
        | 'VENTER_PÅ_BEHANDLING_I_GOSYS'
        | 'VENTER_PÅ_MEDISINSKE_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER'
        | 'VENTER_PÅ_SVAR_FRA_BRUKER'
        | 'VENTER_PÅ_VURDERING_AV_ROL';
    };
    'no.nav.aap.postmottak.api.flyt.Venteinformasjon': {
      begrunnelse: string;
      /**
       * Format: date
       * @example 2025-04-01
       */
      frist: string;
      /** @enum {string} */
      grunn:
        | 'VENTER_PÅ_BEHANDLING_I_GOSYS'
        | 'VENTER_PÅ_MEDISINSKE_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER'
        | 'VENTER_PÅ_OPPLYSNINGER_FRA_UTENLANDSKE_MYNDIGHETER'
        | 'VENTER_PÅ_SVAR_FRA_BRUKER'
        | 'VENTER_PÅ_VURDERING_AV_ROL';
    };
    'no.nav.aap.postmottak.api.test.BehandlingsListe': {
      id: string;
      journalpostId: string;
      /**
       * Format: date-time
       * @example 2025-04-01T12:30:00
       */
      opprettet: string;
      status: string;
      steg: string;
    };
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarFordelingL\u00F8sning': {
      behovstype: string;
      kommentar?: string | null;
      /** @enum {string} */
      valgtSystem: 'ARENA' | 'BEGGE' | 'KELVIN';
    };
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarOverleveringL\u00F8sning': {
      behovstype: string;
      skalOverleveres: boolean;
    };
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarSaksnummerL\u00F8sning': {
      avsenderMottaker?: components['schemas']['no.nav.aap.postmottak.gateway.AvsenderMottakerDto'];
      behovstype: string;
      dokumenter?:
        | components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.ForenkletDokument'][]
        | null;
      'f\u00F8rP\u00E5GenerellSak': boolean;
      journalposttittel?: string | null;
      opprettNySak: boolean;
      saksnummer?: string | null;
    };
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarTemaL\u00F8sning': {
      behovstype: string;
      skalTilAap: boolean;
    };
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklaringsbehovL\u00F8sning':
      | components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarFordelingL\u00F8sning']
      | components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarOverleveringL\u00F8sning']
      | components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarSaksnummerL\u00F8sning']
      | components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.AvklarTemaL\u00F8sning']
      | components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.DigitaliserDokumentL\u00F8sning']
      | components['schemas']['no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.SattP\u00E5VentL\u00F8sning'];
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.DigitaliserDokumentL\u00F8sning': {
      behovstype: string;
      /** @enum {string} */
      kategori:
        | 'AKTIVITETSKORT'
        | 'ANNET_RELEVANT_DOKUMENT'
        | 'DIALOGMELDING'
        | 'FAGSYSTEMINFO_BEHOV_HENDELSE'
        | 'FORELDREPENGE_VEDTAK_HENDELSE'
        | 'INSTITUSJONSOPPHOLD'
        | 'KABAL_HENDELSE'
        | 'KLAGE'
        | 'LEGEERKLÆRING'
        | 'LEGEERKLÆRING_AVVIST'
        | 'MANUELL_REVURDERING'
        | 'MELDEKORT'
        | 'MIGRERING_FRA_ARENA'
        | 'NY_ÅRSAK_TIL_BEHANDLING'
        | 'OMGJØRING_KLAGE_REVURDERING'
        | 'OPPFØLGINGSOPPGAVE'
        | 'PDL_HENDELSE_DODSFALL_BARN'
        | 'PDL_HENDELSE_DODSFALL_BRUKER'
        | 'PDL_HENDELSE_FOLKEREGISTERIDENT'
        | 'SYKEPENGE_VEDTAK_HENDELSE'
        | 'SØKNAD'
        | 'TILBAKEKREVING_HENDELSE'
        | 'UFØRE_VEDTAK_HENDELSE';
      strukturertDokument?: string | null;
      /**
       * Format: date
       * @example 2025-04-01
       */
      's\u00F8knadsdato'?: string | null;
    };
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.ForenkletDokument': {
      dokumentInfoId: string;
      tittel: string;
    };
    'no.nav.aap.postmottak.avklaringsbehov.l\u00F8sning.SattP\u00E5VentL\u00F8sning': {
      behovstype: string;
    };
    'no.nav.aap.postmottak.flyt.flate.visning.Visning': {
      readOnly: boolean;
      /** @enum {string} */
      typeBehandling: 'DokumentHåndtering' | 'Fordeling' | 'Journalføring';
      visVentekort: boolean;
    };
    'no.nav.aap.postmottak.gateway.AvsenderMottakerDto': {
      id?: string | null;
      /** @enum {string|null} */
      idType?: 'FNR' | 'HPRNR' | 'ORGNR' | 'UTL_ORG' | null;
      navn?: string | null;
    };
    'no.nav.aap.postmottak.gateway.Klagebehandling': {
      /** Format: uuid */
      behandlingsReferanse: string;
      /**
       * Format: date
       * @example 2025-04-01
       */
      opprettetDato: string;
    };
    'no.nav.aap.postmottak.joarkavstemmer.UavstemtJournalpost': {
      /** Format: uuid */
      behandlingReferanse?: string | null;
      /**
       * Format: date
       * @example 2025-04-01
       */
      datoOpprettet: string;
      /** Format: int64 */
      journalpostId: number;
      mottaksKanal?: string | null;
    };
    /** Format: uuid */
    'no.nav.aap.postmottak.journalpostogbehandling.behandling.Behandlingsreferanse': string;
    'no.nav.aap.postmottak.journalpostogbehandling.behandling.BehandlingsreferansePathParam': {
      /** Format: uuid */
      referanse: string;
    };
    'no.nav.aap.postmottak.journalpostogbehandling.journalpost.AvsenderMottaker': {
      id?: string | null;
      idType?: string | null;
      navn?: string | null;
    };
    'no.nav.aap.postmottak.journalpostogbehandling.journalpost.Dokument': {
      brevkode: string;
      dokumentInfoId: components['schemas']['no.nav.aap.postmottak.journalpostogbehandling.journalpost.DokumentInfoId'];
      tittel?: string | null;
      varianter: components['schemas']['no.nav.aap.postmottak.journalpostogbehandling.journalpost.Variant'][];
    };
    'no.nav.aap.postmottak.journalpostogbehandling.journalpost.DokumentInfoId': {
      dokumentInfoId: string;
    };
    'no.nav.aap.postmottak.journalpostogbehandling.journalpost.Variant': {
      /** @enum {string} */
      filtype: 'AXML' | 'DXML' | 'JPEG' | 'JSON' | 'PDF' | 'PNG' | 'RTF' | 'TIFF' | 'XLSX' | 'XML';
      /** @enum {string} */
      variantformat: 'ARKIV' | 'FULLVERSJON' | 'ORIGINAL' | 'PRODUKSJON' | 'PRODUKSJON_DLF' | 'SLADDET';
    };
    'no.nav.aap.postmottak.kontrakt.avklaringsbehov.Definisjon': {
      /** @enum {string} */
      kode: '1337' | '1338' | '1339' | '1340' | '1341' | '1342' | '1343' | '9001';
      kreverToTrinn: boolean;
      'l\u00F8sesAv': (
        | 'BESLUTTER'
        | 'DRIFT'
        | 'KVALITETSSIKRER'
        | 'LES'
        | 'PRODUKSJONSSTYRING'
        | 'SAKSBEHANDLER_NASJONAL'
        | 'SAKSBEHANDLER_OPPFOLGING'
      )[];
      /** @enum {string} */
      'l\u00F8sesISteg':
        | 'AVKLAR_FORDELING'
        | 'AVKLAR_FORDELING_VIDERESEND'
        | 'AVKLAR_SAK'
        | 'AVKLAR_TEMA'
        | 'DIGITALISER_DOKUMENT'
        | 'ENDELIG_JOURNALFØRING'
        | 'IVERKSETTES'
        | 'OVERLEVER_TIL_FAGSYSTEM'
        | 'SETT_FAGSAK'
        | 'START_BEHANDLING'
        | 'UDEFINERT'
        | 'VIDERESEND';
      /** @enum {string} */
      type: 'MANUELT_FRIVILLIG' | 'MANUELT_PÅKREVD' | 'VENTEPUNKT';
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
