/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/config/definisjoner': {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': (
              | "MANUELT_SATT_PÅ_VENT(kode='9001')"
              | "AVKLAR_STUDENT(kode='5001')"
              | "AVKLAR_YRKESSKADE(kode='5002')"
              | "AVKLAR_SYKDOM(kode='5003')"
              | "FASTSETT_ARBEIDSEVNE(kode='5004')"
              | "FRITAK_MELDEPLIKT(kode='5005')"
              | "AVKLAR_BISTANDSBEHOV(kode='5006')"
              | "AVKLAR_SYKEPENGEERSTATNING(kode='5007')"
              | "FORESLÅ_VEDTAK(kode='5098')"
              | "FATTE_VEDTAK(kode='5099')"
            )[];
          };
        };
      };
    };
  };
  '/api/sak/finn': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.FinnSakForIdentDTO'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.SaksinfoDTO'][];
          };
        };
      };
    };
  };
  '/api/sak/alle': {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.SaksinfoDTO'][];
          };
        };
      };
    };
  };
  '/api/sak/{saksnummer}': {
    get: {
      parameters: {
        path: {
          /** @description saksnummer */
          saksnummer: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.UtvidetSaksinfoDTO'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.DetaljertBehandlingDTO'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/flyt': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.BehandlingFlytOgTilstandDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/fatte-vedtak': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.flate.FatteVedtakGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/bistand': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.flate.BistandGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/fritak-meldeplikt': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.flate.FritakMeldepliktGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/medlemskap': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.medlemskap.MedlemskapGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/student': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.flate.StudentGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/sykdom/sykdom': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykdomGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/sykdom/yrkesskade': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.YrkesskadeGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/løs-behov': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.flate.LøsAvklaringsbehovPåBehandling'];
        };
      };
      responses: {
        202: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.flate.LøsAvklaringsbehovPåBehandling'];
          };
        };
      };
    };
  };
  '/test/opprett': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestcaseDTO'];
        };
      };
      responses: {
        202: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestcaseDTO'];
          };
        };
      };
    };
  };
  '/test/pliktkort': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.PliktkortTestDTO'];
        };
      };
      responses: {
        202: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.PliktkortTestDTO'];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    'no.nav.aap.behandlingsflyt.OpprettTestcaseDTO': {
      /**
       * Format: date
       * @example 2024-02-05
       */
      fødselsdato: string;
      ident: string;
      yrkesskade: boolean;
    };
    'no.nav.aap.behandlingsflyt.PliktkortTestDTO': {
      ident: string;
      pliktkort: components['schemas']['no.nav.aap.behandlingsflyt.hendelse.mottak.dokument.pliktkort.Pliktkort'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.flate.FatteVedtakGrunnlagDto': {
      vurderinger: components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løser.vedtak.TotrinnsVurdering'][];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.flate.LøsAvklaringsbehovPåBehandling': {
      /** Format: int64 */
      behandlingVersjon: number;
      behov: components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løser.AvklaringsbehovLøsning'];
      ingenEndringIGruppe: boolean;
      /** Format: uuid */
      referanse: string;
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løser.AvklaringsbehovLøsning': Record<string, never>;
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løser.vedtak.TotrinnsVurdering': {
      begrunnelse?: string | null;
      definisjon: string;
      godkjent?: boolean | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.dokument.arbeid.ArbeidIPeriode': {
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      timerArbeid: components['schemas']['no.nav.aap.verdityper.TimerArbeid'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.BistandVurdering': {
      begrunnelse: string;
      erBehovForBistand: boolean;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.flate.BistandGrunnlagDto': {
      vurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.BistandVurdering'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.medlemskap.MedlemskapGrunnlagDto': Record<string, never>;
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.Fritaksvurdering': {
      begrunnelse: string;
      harFritak: boolean;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.flate.FritakMeldepliktGrunnlagDto': {
      vurderinger: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.Fritaksvurdering'][];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.StudentVurdering': {
      /**
       * Format: date
       * @example 2024-02-05
       */
      avbruttStudieDato?: string | null;
      begrunnelse: string;
      dokumenterBruktIVurdering: components['schemas']['no.nav.aap.verdityper.dokument.JournalpostId'][];
      oppfyller11_14?: boolean | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.flate.StudentGrunnlagDto': {
      studentvurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.StudentVurdering'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.Sykdomsvurdering': {
      begrunnelse: string;
      dokumenterBruktIVurdering: components['schemas']['no.nav.aap.verdityper.dokument.JournalpostId'][];
      erNedsettelseIArbeidsevneHøyereEnnNedreGrense?: boolean | null;
      erSkadeSykdomEllerLyteVesentligdel: boolean;
      /** @enum {string|null} */
      nedreGrense?: 'TRETTI' | 'FEMTI' | null;
      /**
       * Format: date
       * @example 2024-02-05
       */
      nedsattArbeidsevneDato?: string | null;
      /**
       * Format: date
       * @example 2024-02-05
       */
      ytterligereNedsattArbeidsevneDato?: string | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.Yrkesskadevurdering': {
      andelAvNedsettelse?: components['schemas']['no.nav.aap.verdityper.Prosent'];
      antattÅrligInntekt?: components['schemas']['no.nav.aap.verdityper.Beløp'];
      begrunnelse: string;
      dokumenterBruktIVurdering: components['schemas']['no.nav.aap.verdityper.dokument.JournalpostId'][];
      erÅrsakssammenheng: boolean;
      /**
       * Format: date
       * @example 2024-02-05
       */
      skadetidspunkt?: string | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.InnhentetSykdomsOpplysninger': {
      innhentedeYrkesskader: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.RegistrertYrkesskade'][];
      oppgittYrkesskadeISøknad: boolean;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.RegistrertYrkesskade': {
      kilde: string;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      ref: string;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykdomGrunnlagDto': {
      erÅrsakssammenheng?: boolean | null;
      opplysninger: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.InnhentetSykdomsOpplysninger'];
      sykdomsvurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.Sykdomsvurdering'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.YrkesskadeGrunnlagDto': {
      opplysninger: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.InnhentetSykdomsOpplysninger'];
      yrkesskadevurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.Yrkesskadevurdering'];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.AvklaringsbehovDTO': {
      /** @enum {string} */
      definisjon:
        | "MANUELT_SATT_PÅ_VENT(kode='9001')"
        | "AVKLAR_STUDENT(kode='5001')"
        | "AVKLAR_YRKESSKADE(kode='5002')"
        | "AVKLAR_SYKDOM(kode='5003')"
        | "FASTSETT_ARBEIDSEVNE(kode='5004')"
        | "FRITAK_MELDEPLIKT(kode='5005')"
        | "AVKLAR_BISTANDSBEHOV(kode='5006')"
        | "AVKLAR_SYKEPENGEERSTATNING(kode='5007')"
        | "FORESLÅ_VEDTAK(kode='5098')"
        | "FATTE_VEDTAK(kode='5099')";
      endringer: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.EndringDTO'][];
      /** @enum {string} */
      status: 'OPPRETTET' | 'AVSLUTTET' | 'TOTRINNS_VURDERT' | 'SENDT_TILBAKE_FRA_BESLUTTER' | 'AVBRUTT';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.BehandlingFlytOgTilstandDto': {
      /** @enum {string} */
      aktivGruppe:
        | 'START_BEHANDLING'
        | 'ALDER'
        | 'LOVVALG'
        | 'MEDLEMSKAP'
        | 'BARNETILLEGG'
        | 'SAMORDNING'
        | 'SYKDOM'
        | 'GRUNNLAG'
        | 'UTTAK'
        | 'TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'VEDTAK'
        | 'UDEFINERT';
      /** @enum {string} */
      aktivtSteg:
        | 'START_BEHANDLING'
        | 'VURDER_ALDER'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'AVKLAR_STUDENT'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'FRITAK_MELDEPLIKT'
        | 'BARNETILLEGG'
        | 'SAMORDNING'
        | 'AVKLAR_YRKESSKADE'
        | 'AVKLAR_SYKDOM'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_UTTAK'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'FORESLÅ_VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
      /** Format: int64 */
      behandlingVersjon: number;
      flyt: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.FlytGruppe'][];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.DetaljertBehandlingDTO': {
      /** @enum {string} */
      aktivtSteg:
        | 'START_BEHANDLING'
        | 'VURDER_ALDER'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'AVKLAR_STUDENT'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'FRITAK_MELDEPLIKT'
        | 'BARNETILLEGG'
        | 'SAMORDNING'
        | 'AVKLAR_YRKESSKADE'
        | 'AVKLAR_SYKDOM'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_UTTAK'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'FORESLÅ_VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
      avklaringsbehov: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.AvklaringsbehovDTO'][];
      /**
       * Format: date-time
       * @example 2024-02-05T15:50:51.083383
       */
      opprettet: string;
      /** Format: uuid */
      referanse: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'UTREDES' | 'AVSLUTTET' | 'PÅ_VENT';
      type: string;
      /** Format: int64 */
      versjon: number;
      vilkår: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.VilkårDTO'][];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.EndringDTO': {
      begrunnelse: string;
      endretAv: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'AVSLUTTET' | 'TOTRINNS_VURDERT' | 'SENDT_TILBAKE_FRA_BESLUTTER' | 'AVBRUTT';
      /**
       * Format: date-time
       * @example 2024-02-05T15:50:51.083383
       */
      tidsstempel: string;
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.FlytGruppe': {
      erFullført: boolean;
      steg: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.FlytSteg'][];
      /** @enum {string} */
      stegGruppe:
        | 'START_BEHANDLING'
        | 'ALDER'
        | 'LOVVALG'
        | 'MEDLEMSKAP'
        | 'BARNETILLEGG'
        | 'SAMORDNING'
        | 'SYKDOM'
        | 'GRUNNLAG'
        | 'UTTAK'
        | 'TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'VEDTAK'
        | 'UDEFINERT';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.FlytSteg': {
      avklaringsbehov: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.AvklaringsbehovDTO'][];
      /** @enum {string} */
      stegType:
        | 'START_BEHANDLING'
        | 'VURDER_ALDER'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'AVKLAR_STUDENT'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'FRITAK_MELDEPLIKT'
        | 'BARNETILLEGG'
        | 'SAMORDNING'
        | 'AVKLAR_YRKESSKADE'
        | 'AVKLAR_SYKDOM'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_UTTAK'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'FORESLÅ_VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
      vilkårDTO?: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.VilkårDTO'];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.VilkårDTO': {
      perioder: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.VilkårsperiodeDTO'][];
      /** @enum {string} */
      vilkårtype: 'ALDERSVILKÅRET' | 'SYKDOMSVILKÅRET' | 'BISTANDSVILKÅRET' | 'GRUNNLAGET' | 'SYKEPENGEERSTATNING';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.VilkårsperiodeDTO': {
      /** @enum {string|null} */
      avslagsårsak?:
        | 'BRUKER_UNDER_18'
        | 'BRUKER_OVER_67'
        | 'MANGLENDE_DOKUMENTASJON'
        | 'IKKE_SYKDOM_SKADE_LYTE_VESENTLIGDEL'
        | 'IKKE_NOK_REDUSERT_ARBEIDSEVNE'
        | null;
      begrunnelse?: string | null;
      /** @enum {string|null} */
      innvilgelsesårsak?: 'YRKESSKADE_ÅRSAKSSAMMENHENG' | 'STUDENT' | null;
      manuellVurdering: boolean;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      /** @enum {string} */
      utfall: 'IKKE_VURDERT' | 'IKKE_RELEVANT' | 'OPPFYLT' | 'IKKE_OPPFYLT';
    };
    'no.nav.aap.behandlingsflyt.hendelse.mottak.dokument.pliktkort.Pliktkort': {
      timerArbeidPerPeriode: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.dokument.arbeid.ArbeidIPeriode'][];
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.BehandlinginfoDTO': {
      /**
       * Format: date-time
       * @example 2024-02-05T15:50:51.083383
       */
      opprettet: string;
      /** Format: uuid */
      referanse: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'UTREDES' | 'AVSLUTTET' | 'PÅ_VENT';
      type: string;
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.FinnSakForIdentDTO': {
      ident: string;
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.SaksinfoDTO': {
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      saksnummer: string;
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.UtvidetSaksinfoDTO': {
      behandlinger: components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.BehandlinginfoDTO'][];
      ident: string;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      saksnummer: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'UTREDES' | 'LØPENDE' | 'AVSLUTTET';
    };
    'no.nav.aap.verdityper.Beløp': Record<string, never>;
    'no.nav.aap.verdityper.Periode': {
      /**
       * Format: date
       * @example 2024-02-05
       */
      fom: string;
      /**
       * Format: date
       * @example 2024-02-05
       */
      tom: string;
    };
    'no.nav.aap.verdityper.Prosent': Record<string, never>;
    'no.nav.aap.verdityper.TimerArbeid': {
      antallTimer: number;
    };
    'no.nav.aap.verdityper.dokument.JournalpostId': {
      identifikator: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
