/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/config/definisjoner': {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': (
              | "MANUELT_SATT_PÅ_VENT(kode='9001')"
              | "AVKLAR_STUDENT(kode='5001')"
              | "AVKLAR_SYKDOM(kode='5003')"
              | "FASTSETT_ARBEIDSEVNE(kode='5004')"
              | "FASTSETT_BEREGNINGSTIDSPUNKT(kode='5008')"
              | "FRITAK_MELDEPLIKT(kode='5005')"
              | "AVKLAR_BISTANDSBEHOV(kode='5006')"
              | "AVKLAR_SYKEPENGEERSTATNING(kode='5007')"
              | "FORESLÅ_VEDTAK(kode='5098')"
              | "FATTE_VEDTAK(kode='5099')"
            )[];
          };
        };
      };
    };
  };
  '/api/sak/finn': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.FinnSakForIdentDTO'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.SaksinfoDTO'][];
          };
        };
      };
    };
  };
  '/api/sak/finnEllerOpprett': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.FinnEllerOpprettSakDTO'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.SaksinfoDTO'];
          };
        };
      };
    };
  };
  '/api/sak/alle': {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.SaksinfoDTO'][];
          };
        };
      };
    };
  };
  '/api/sak/{saksnummer}': {
    get: {
      parameters: {
        path: {
          /** @description saksnummer */
          saksnummer: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.UtvidetSaksinfoDTO'];
          };
        };
      };
    };
  };
  '/api/soknad/send': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.SøknadSendDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': string;
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.DetaljertBehandlingDTO'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/flyt': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.BehandlingFlytOgTilstandDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/resultat': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.BehandlingResultatDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/fatte-vedtak': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.flate.FatteVedtakGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/bistand': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.flate.BistandGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/fritak-meldeplikt': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.flate.FritakMeldepliktGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/medlemskap': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.medlemskap.MedlemskapGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/student': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.flate.StudentGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/sykdom/sykdom': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykdomGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/sykdom/sykepengergrunnlag': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykepengerGrunnlagDto'];
          };
        };
      };
    };
  };
  '/api/behandling/løs-behov': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.flate.LøsAvklaringsbehovPåBehandling'];
        };
      };
      responses: {
        202: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.flate.LøsAvklaringsbehovPåBehandling'];
          };
        };
      };
    };
  };
  '/api/behandling/tilkjent/{referanse}': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.tilkjentytelse.flate.TilkjentYtelseDto'];
          };
        };
      };
    };
  };
  '/api/behandling/{referanse}/grunnlag/beregningsvurdering': {
    get: {
      parameters: {
        path: {
          /** @description referanse */
          referanse: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.beregning.flate.BeregningsVurderingDTO'];
          };
        };
      };
    };
  };
  '/test/opprett': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestcaseDTO'];
        };
      };
      responses: {
        202: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestcaseDTO'];
          };
        };
      };
    };
  };
  '/test/pliktkort': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.PliktkortTestDTO'];
        };
      };
      responses: {
        202: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.PliktkortTestDTO'];
          };
        };
      };
    };
  };
  '/testdataApi/opprettPerson': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestcaseDTO'];
        };
      };
      responses: {
        202: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestcaseDTO'];
          };
        };
      };
    };
  };
  '/testdataApi/genererPerson': {
    post: {
      requestBody?: {
        content: {
          'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestPersonDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['no.nav.aap.behandlingsflyt.OpprettTestPersonResponsDto'];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    'no.nav.aap.behandlingsflyt.OpprettTestPersonDto': {
      /**
       * Format: date
       * @example 2024-04-30
       */
      fødselsdato: string;
      yrkesskade: boolean;
    };
    'no.nav.aap.behandlingsflyt.OpprettTestPersonResponsDto': {
      ident: string;
    };
    'no.nav.aap.behandlingsflyt.OpprettTestcaseDTO': {
      /**
       * Format: date
       * @example 2024-04-30
       */
      fødselsdato: string;
      ident: string;
      student: boolean;
      yrkesskade: boolean;
    };
    'no.nav.aap.behandlingsflyt.PliktkortTestDTO': {
      ident: string;
      pliktkort: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.dokument.kontrakt.pliktkort.Pliktkort'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.flate.FatteVedtakGrunnlagDto': {
      historikk: components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.flate.Historikk'][];
      vurderinger: components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løser.vedtak.TotrinnsVurdering'][];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.flate.Historikk': {
      /** @enum {string} */
      aksjon: 'SENDT_TIL_BESLUTTER' | 'RETURNERT_FRA_BESLUTTER' | 'FATTET_VEDTAK';
      avIdent: string;
      /**
       * Format: date-time
       * @example 2024-04-30T14:08:19.011798
       */
      tidspunkt: string;
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.flate.LøsAvklaringsbehovPåBehandling': {
      /** Format: int64 */
      behandlingVersjon: number;
      behov: components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklaringsbehovLøsning'];
      ingenEndringIGruppe?: boolean | null;
      /** Format: uuid */
      referanse: string;
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løser.vedtak.TotrinnsVurdering': {
      begrunnelse?: string | null;
      definisjon: string;
      godkjent?: boolean | null;
      grunner?: components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.ÅrsakTilRetur'][] | null;
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarBistandsbehovLøsning': {
      behovstype: string;
      bistandsVurdering: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.BistandVurdering'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarStudentLøsning': {
      behovstype: string;
      studentvurdering: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.StudentVurdering'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarSykdomLøsning': {
      behovstype: string;
      sykdomsvurdering: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykdomsvurderingDto'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarSykepengerErstatningLøsning': {
      behovstype: string;
      sykepengeerstatningVurdering: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.SykepengerVurdering'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklaringsbehovLøsning':
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarBistandsbehovLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarStudentLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarSykdomLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.AvklarSykepengerErstatningLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FastsettArbeidsevneLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FastsettBeregningstidspunktLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FatteVedtakLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.ForeslåVedtakLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FritakMeldepliktLøsning']
      | components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.SattPåVentLøsning'];
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FastsettArbeidsevneLøsning': {
      arbeidsevne: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.arbeidsevne.Arbeidsevne'];
      behovstype: string;
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FastsettBeregningstidspunktLøsning': {
      behovstype: string;
      beregningVurdering: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.beregning.BeregningVurdering'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FatteVedtakLøsning': {
      behovstype: string;
      vurderinger: components['schemas']['no.nav.aap.behandlingsflyt.avklaringsbehov.løser.vedtak.TotrinnsVurdering'][];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.ForeslåVedtakLøsning': {
      behovstype: string;
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.FritakMeldepliktLøsning': {
      behovstype: string;
      vurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.Fritaksvurdering'];
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.løsning.SattPåVentLøsning': {
      behovstype: string;
    };
    'no.nav.aap.behandlingsflyt.avklaringsbehov.ÅrsakTilRetur': {
      /** @enum {string} */
      årsak: 'MANGELFULL_BEGRUNNELSE' | 'MANGLENDE_UTREDNING' | 'FEIL_LOVANVENDELSE' | 'ANNET';
      årsakFritekst?: string | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.dokument.arbeid.ArbeidIPeriode': {
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      timerArbeid: components['schemas']['no.nav.aap.verdityper.TimerArbeid'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.dokument.kontrakt.pliktkort.Pliktkort': {
      timerArbeidPerPeriode: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.dokument.arbeid.ArbeidIPeriode'][];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.arbeidsevne.Arbeidsevne': {
      arbeidsevne: components['schemas']['no.nav.aap.verdityper.Prosent'];
      begrunnelse: string;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.beregning.BeregningVurdering': {
      antattÅrligInntekt?: components['schemas']['no.nav.aap.verdityper.Beløp'];
      begrunnelse: string;
      /**
       * Format: date
       * @example 2024-04-30
       */
      ytterligereNedsattArbeidsevneDato?: string | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.beregning.flate.BeregningsVurderingDTO': {
      antattÅrligInntekt?: number | null;
      begrunnelse?: string | null;
      /**
       * Format: date
       * @example 2024-04-30
       */
      ytterligereNedsattArbeidsevneDato?: string | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.BistandVurdering': {
      begrunnelse: string;
      erBehovForBistand: boolean;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.flate.BistandGrunnlagDto': {
      vurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.bistand.BistandVurdering'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.medlemskap.MedlemskapGrunnlagDto': Record<string, never>;
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.Fritaksvurdering': {
      begrunnelse: string;
      harFritak: boolean;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.flate.FritakMeldepliktGrunnlagDto': {
      vurderinger: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.meldeplikt.Fritaksvurdering'][];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.StudentVurdering': {
      /**
       * Format: date
       * @example 2024-04-30
       */
      avbruttStudieDato?: string | null;
      begrunnelse: string;
      dokumenterBruktIVurdering: components['schemas']['no.nav.aap.verdityper.dokument.JournalpostId'][];
      /** Format: int64 */
      id?: number | null;
      oppfyller11_14?: boolean | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.flate.StudentGrunnlagDto': {
      studentvurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.student.StudentVurdering'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.SykepengerVurdering': {
      begrunnelse: string;
      dokumenterBruktIVurdering: components['schemas']['no.nav.aap.verdityper.dokument.JournalpostId'][];
      harRettPå?: boolean | null;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.InnhentetSykdomsOpplysninger': {
      innhentedeYrkesskader: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.RegistrertYrkesskade'][];
      oppgittYrkesskadeISøknad: boolean;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.RegistrertYrkesskade': {
      kilde: string;
      ref: string;
      /**
       * Format: date
       * @example 2024-04-30
       */
      skadedato: string;
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykdomGrunnlagDto': {
      opplysninger: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.InnhentetSykdomsOpplysninger'];
      skalVurdereYrkesskade: boolean;
      sykdomsvurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykdomsvurderingDto'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykdomsvurderingDto': {
      begrunnelse: string;
      dokumenterBruktIVurdering: components['schemas']['no.nav.aap.verdityper.dokument.JournalpostId'][];
      erArbeidsevnenNedsatt: boolean;
      erNedsettelseIArbeidsevneHøyereEnnNedreGrense?: boolean | null;
      erSkadeSykdomEllerLyteVesentligdel?: boolean | null;
      /** @enum {string|null} */
      nedreGrense?: 'TRETTI' | 'FEMTI' | null;
      /**
       * Format: date
       * @example 2024-04-30
       */
      nedsattArbeidsevneDato?: string | null;
      yrkesskadevurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.YrkesskadevurderingDto'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.SykepengerGrunnlagDto': {
      vurdering?: components['schemas']['no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.SykepengerVurdering'];
    };
    'no.nav.aap.behandlingsflyt.faktagrunnlag.saksbehandler.sykdom.flate.YrkesskadevurderingDto': {
      erÅrsakssammenheng: boolean;
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.AvklaringsbehovDTO': {
      /** @enum {string} */
      definisjon:
        | "MANUELT_SATT_PÅ_VENT(kode='9001')"
        | "AVKLAR_STUDENT(kode='5001')"
        | "AVKLAR_SYKDOM(kode='5003')"
        | "FASTSETT_ARBEIDSEVNE(kode='5004')"
        | "FASTSETT_BEREGNINGSTIDSPUNKT(kode='5008')"
        | "FRITAK_MELDEPLIKT(kode='5005')"
        | "AVKLAR_BISTANDSBEHOV(kode='5006')"
        | "AVKLAR_SYKEPENGEERSTATNING(kode='5007')"
        | "FORESLÅ_VEDTAK(kode='5098')"
        | "FATTE_VEDTAK(kode='5099')";
      endringer: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.EndringDTO'][];
      /** @enum {string} */
      status: 'OPPRETTET' | 'AVSLUTTET' | 'TOTRINNS_VURDERT' | 'SENDT_TILBAKE_FRA_BESLUTTER' | 'AVBRUTT';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.BehandlingFlytOgTilstandDto': {
      /** @enum {string} */
      aktivGruppe:
        | 'START_BEHANDLING'
        | 'ALDER'
        | 'LOVVALG'
        | 'MEDLEMSKAP'
        | 'BARNETILLEGG'
        | 'SYKDOM'
        | 'GRUNNLAG'
        | 'UTTAK'
        | 'TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
      /** @enum {string} */
      aktivtSteg:
        | 'START_BEHANDLING'
        | 'VURDER_ALDER'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'AVKLAR_STUDENT'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'FRITAK_MELDEPLIKT'
        | 'BARNETILLEGG'
        | 'AVKLAR_SYKDOM'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_BEREGNINGSTIDSPUNKT'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_UTTAK'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'FORESLÅ_VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
      /** Format: int64 */
      behandlingVersjon: number;
      flyt: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.FlytGruppe'][];
      prosessering: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.Prosessering'];
      visning: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.Visning'];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.BehandlingResultatDto': {
      vilkårene: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.VilkårDTO'][];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.DetaljertBehandlingDTO': {
      /** @enum {string} */
      aktivtSteg:
        | 'START_BEHANDLING'
        | 'VURDER_ALDER'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'AVKLAR_STUDENT'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'FRITAK_MELDEPLIKT'
        | 'BARNETILLEGG'
        | 'AVKLAR_SYKDOM'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_BEREGNINGSTIDSPUNKT'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_UTTAK'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'FORESLÅ_VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
      avklaringsbehov: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.AvklaringsbehovDTO'][];
      /**
       * Format: date-time
       * @example 2024-04-30T14:08:19.011798
       */
      opprettet: string;
      /** Format: uuid */
      referanse: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'UTREDES' | 'AVSLUTTET' | 'PÅ_VENT';
      type: string;
      /** Format: int64 */
      versjon: number;
      vilkår: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.VilkårDTO'][];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.EndringDTO': {
      begrunnelse?: string | null;
      endretAv: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'AVSLUTTET' | 'TOTRINNS_VURDERT' | 'SENDT_TILBAKE_FRA_BESLUTTER' | 'AVBRUTT';
      /**
       * Format: date-time
       * @example 2024-04-30T14:08:19.011798
       */
      tidsstempel: string;
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.FlytGruppe': {
      erFullført: boolean;
      steg: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.FlytSteg'][];
      /** @enum {string} */
      stegGruppe:
        | 'START_BEHANDLING'
        | 'ALDER'
        | 'LOVVALG'
        | 'MEDLEMSKAP'
        | 'BARNETILLEGG'
        | 'SYKDOM'
        | 'GRUNNLAG'
        | 'UTTAK'
        | 'TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.FlytSteg': {
      avklaringsbehov: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.AvklaringsbehovDTO'][];
      /** @enum {string} */
      stegType:
        | 'START_BEHANDLING'
        | 'VURDER_ALDER'
        | 'VURDER_LOVVALG'
        | 'VURDER_MEDLEMSKAP'
        | 'AVKLAR_STUDENT'
        | 'VURDER_BISTANDSBEHOV'
        | 'VURDER_SYKEPENGEERSTATNING'
        | 'FRITAK_MELDEPLIKT'
        | 'BARNETILLEGG'
        | 'AVKLAR_SYKDOM'
        | 'FASTSETT_ARBEIDSEVNE'
        | 'FASTSETT_BEREGNINGSTIDSPUNKT'
        | 'FASTSETT_GRUNNLAG'
        | 'FASTSETT_UTTAK'
        | 'BEREGN_TILKJENT_YTELSE'
        | 'SIMULERING'
        | 'FORESLÅ_VEDTAK'
        | 'FATTE_VEDTAK'
        | 'IVERKSETT_VEDTAK'
        | 'UDEFINERT';
      vilkårDTO?: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.VilkårDTO'];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.OppgaveDto': {
      oppgaveType: string;
      /** @enum {string} */
      status: 'KLAR' | 'PLUKKET' | 'FERDIG' | 'FEILET';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.Prosessering': {
      /** @enum {string} */
      status: 'JOBBER' | 'FEILET' | 'FERDIG';
      ventendeOppgaver: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.OppgaveDto'][];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.SøknadDto': {
      student: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.SøknadStudentDto'];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.SøknadSendDto': {
      journalpostId: string;
      saksnummer: string;
      søknad: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.SøknadDto'];
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.SøknadStudentDto': {
      erStudent: string;
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.VilkårDTO': {
      perioder: components['schemas']['no.nav.aap.behandlingsflyt.flyt.flate.VilkårsperiodeDTO'][];
      /** @enum {string} */
      vilkårtype:
        | 'ALDERSVILKÅRET'
        | 'SYKDOMSVILKÅRET'
        | 'BISTANDSVILKÅRET'
        | 'MEDLEMSKAP'
        | 'GRUNNLAGET'
        | 'SYKEPENGEERSTATNING';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.VilkårsperiodeDTO': {
      /** @enum {string|null} */
      avslagsårsak?:
        | 'BRUKER_UNDER_18'
        | 'BRUKER_OVER_67'
        | 'MANGLENDE_DOKUMENTASJON'
        | 'IKKE_SYKDOM_SKADE_LYTE_VESENTLIGDEL'
        | 'IKKE_NOK_REDUSERT_ARBEIDSEVNE'
        | null;
      begrunnelse?: string | null;
      /** @enum {string|null} */
      innvilgelsesårsak?: 'YRKESSKADE_ÅRSAKSSAMMENHENG' | 'STUDENT' | null;
      manuellVurdering: boolean;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      /** @enum {string} */
      utfall: 'IKKE_VURDERT' | 'IKKE_RELEVANT' | 'OPPFYLT' | 'IKKE_OPPFYLT';
    };
    'no.nav.aap.behandlingsflyt.flyt.flate.Visning': {
      beslutterReadOnly: boolean;
      saksbehandlerReadOnly: boolean;
      visBeslutterKort: boolean;
    };
    'no.nav.aap.behandlingsflyt.forretningsflyt.steg.Tilkjent': {
      /** Format: int32 */
      antallBarn: number;
      barnetillegg: components['schemas']['no.nav.aap.verdityper.Beløp'];
      barnetilleggsats: components['schemas']['no.nav.aap.verdityper.Beløp'];
      dagsats: components['schemas']['no.nav.aap.verdityper.Beløp'];
      gradering: components['schemas']['no.nav.aap.verdityper.Prosent'];
      grunnbeløp: components['schemas']['no.nav.aap.verdityper.Beløp'];
      grunnlag: components['schemas']['no.nav.aap.verdityper.Beløp'];
      grunnlagsfaktor: components['schemas']['no.nav.aap.verdityper.GUnit'];
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.BehandlinginfoDTO': {
      /**
       * Format: date-time
       * @example 2024-04-30T14:08:19.011798
       */
      opprettet: string;
      /** Format: uuid */
      referanse: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'UTREDES' | 'AVSLUTTET' | 'PÅ_VENT';
      type: string;
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.FinnEllerOpprettSakDTO': {
      ident: string;
      /**
       * Format: date
       * @example 2024-04-30
       */
      søknadsdato: string;
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.FinnSakForIdentDTO': {
      ident: string;
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.SaksinfoDTO': {
      ident: string;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      saksnummer: string;
    };
    'no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.UtvidetSaksinfoDTO': {
      behandlinger: components['schemas']['no.nav.aap.behandlingsflyt.sakogbehandling.sak.flate.BehandlinginfoDTO'][];
      ident: string;
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      saksnummer: string;
      /** @enum {string} */
      status: 'OPPRETTET' | 'UTREDES' | 'LØPENDE' | 'AVSLUTTET';
    };
    'no.nav.aap.behandlingsflyt.tilkjentytelse.flate.TilkjentYtelseDto': {
      perioder: components['schemas']['no.nav.aap.behandlingsflyt.tilkjentytelse.flate.TilkjentYtelsePeriode'][];
    };
    'no.nav.aap.behandlingsflyt.tilkjentytelse.flate.TilkjentYtelsePeriode': {
      periode: components['schemas']['no.nav.aap.verdityper.Periode'];
      tilkjent: components['schemas']['no.nav.aap.behandlingsflyt.forretningsflyt.steg.Tilkjent'];
    };
    'no.nav.aap.verdityper.Beløp': {
      verdi: number;
    };
    'no.nav.aap.verdityper.GUnit': {
      verdi: number;
    };
    'no.nav.aap.verdityper.Periode': {
      /**
       * Format: date
       * @example 2024-04-30
       */
      fom: string;
      /**
       * Format: date
       * @example 2024-04-30
       */
      tom: string;
    };
    'no.nav.aap.verdityper.Prosent': Record<string, never>;
    'no.nav.aap.verdityper.TimerArbeid': {
      antallTimer: number;
    };
    'no.nav.aap.verdityper.dokument.JournalpostId': {
      identifikator: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
