import { logError } from 'lib/serverutlis/logger';
import { NextRequest } from 'next/server';

export type Kommune = {
  code: string;
  name: string;
};
const kommuner: Kommune[] = [
  { code: '0301', name: 'Oslo' },
  { code: '1101	', name: 'Eigersund' },
  { code: '1103	', name: 'Stavanger' },
  { code: '1106	', name: 'Haugesund' },
  { code: '1108	', name: 'Sandnes' },
  { code: '1111	', name: 'Sokndal' },
  { code: '1112	', name: 'Lund' },
  { code: '1114	', name: 'Bjerkreim' },
  { code: '1127	', name: 'Randaberg' },
  { code: '1130	', name: 'Strand' },
  { code: '1133	', name: 'Hjelmeland' },
  { code: '1134	', name: 'Suldal' },
  { code: '1135	', name: 'Sauda' },
  { code: '1144	', name: 'Kvits¯y' },
  { code: '1145	', name: 'Bokn' },
  { code: '1146	', name: 'TysvÊr' },
  { code: '1149	', name: 'Karm¯y' },
  { code: '1151	', name: 'Utsira' },
  { code: '1160	', name: 'Vindafjord' },
  { code: '1505	', name: 'Kristiansund' },
  { code: '1506	', name: 'Molde' },
  { code: '1511	', name: 'Vanylven' },
  { code: '1514	', name: 'Sande' },
  { code: '1516	', name: 'Ulstein' },
  { code: '1517	', name: 'Hareid' },
  { code: '1520	', name: 'ÿrsta' },
  { code: '1525	', name: 'Stranda' },
  { code: '1528	', name: 'Sykkylven' },
  { code: '1531	', name: 'Sula' },
  { code: '1532	', name: 'Giske' },
  { code: '1535	', name: 'Vestnes' },
  { code: '1539	', name: 'Rauma' },
  { code: '1547	', name: 'Aukra' },
  { code: '1554	', name: 'Aver¯y' },
  { code: '1557	', name: 'Gjemnes' },
  { code: '1560	', name: 'Tingvoll' },
  { code: '1563	', name: 'Sunndal' },
  { code: '1566	', name: 'Surnadal' },
  { code: '1579	', name: 'Hustadvika' },
  { code: '1580	', name: 'Haram' },
  { code: '1816	', name: 'Vevelstad' },
  { code: '1820	', name: 'Alstahaug' },
  { code: '1822	', name: 'Leirfjord' },
  { code: '1824	', name: 'Vefsn' },
  { code: '1825	', name: 'Grane' },
  { code: '1826	', name: 'Aarborte - Hattfjelldal' },
  { code: '1838	', name: 'GildeskÂl' },
  { code: '1839	', name: 'Beiarn' },
  { code: '1840	', name: 'Saltdal' },
  { code: '1841	', name: 'Fauske - Fuossko' },
  { code: '1848	', name: 'Steigen' },
  { code: '1853	', name: 'Evenes - Even·??i' },
  { code: '1868	', name: 'ÿksnes' },
  { code: '1870	', name: 'Sortland - Suort·' },
  { code: '1874	', name: 'Moskenes' },
  { code: '3101	', name: 'Halden' },
  { code: '3103	', name: 'Moss' },
  { code: '3105	', name: 'Sarpsborg' },
  { code: '3107	', name: 'Fredrikstad' },
  { code: '3110	', name: 'Hvaler' },
  { code: '3112	', name: 'RÂde' },
  { code: '3114	', name: 'VÂler (ÿstfold)' },
  { code: '3116	', name: 'Skiptvet' },
  { code: '3118	', name: 'Indre ÿstfold' },
  { code: '3120	', name: 'Rakkestad' },
  { code: '3122	', name: 'Marker' },
  { code: '3124	', name: 'Aremark' },
  { code: '3201	', name: 'BÊrum' },
  { code: '3203	', name: 'Asker' },
  { code: '3205	', name: 'Lillestr¯m' },
  { code: '3207	', name: 'Nordre Follo' },
  { code: '3209	', name: 'Ullensaker' },
  { code: '3212	', name: 'Nesodden' },
  { code: '3214	', name: 'Frogn' },
  { code: '3216	', name: 'Vestby' },
  { code: '3220	', name: 'Enebakk' },
  { code: '3224	', name: 'RÊlingen' },
  { code: '3226	', name: 'Aurskog-H¯land' },
  { code: '3230	', name: 'Gjerdrum' },
  { code: '3232	', name: 'Nittedal' },
  { code: '3234	', name: 'Lunner' },
  { code: '3236	', name: 'Jevnaker' },
  { code: '3238	', name: 'Nannestad' },
  { code: '3240	', name: 'Eidsvoll' },
  { code: '3242	', name: 'Hurdal' },
  { code: '3301	', name: 'Drammen' },
  { code: '3303	', name: 'Kongsberg' },
  { code: '3305	', name: 'Ringerike' },
  { code: '3310	', name: 'Hole' },
  { code: '3312	', name: 'Lier' },
  { code: '3314	', name: 'ÿvre Eiker' },
  { code: '3316	', name: 'Modum' },
  { code: '3322	', name: 'Nesbyen' },
  { code: '3326	', name: 'Hemsedal' },
  { code: '3405	', name: 'Lillehammer' },
  { code: '3411	', name: 'Ringsaker' },
  { code: '3413	', name: 'Stange' },
  { code: '3414	', name: 'Nord-Odal' },
  { code: '3416	', name: 'Eidskog' },
  { code: '3417	', name: 'Grue' },
  { code: '3419	', name: 'VÂler (Innlandet)' },
  { code: '3420	', name: 'Elverum' },
  { code: '3421	', name: 'Trysil' },
  { code: '3424	', name: 'Rendalen' },
  { code: '3425	', name: 'Engerdal' },
  { code: '3426	', name: 'Tolga' },
  { code: '3427	', name: 'Tynset' },
  { code: '3428	', name: 'Alvdal' },
  { code: '3429	', name: 'Folldal' },
  { code: '3903	', name: 'Holmestrand' },
  { code: '3907	', name: 'Sandefjord' },
  { code: '3909	', name: 'Larvik' },
  { code: '3911	', name: 'FÊrder' },
  { code: '4001	', name: 'Porsgrunn' },
  { code: '4003	', name: 'Skien' },
  { code: '4005	', name: 'Notodden' },
  { code: '4010	', name: 'Siljan' },
  { code: '4012	', name: 'Bamble' },
  { code: '4014	', name: 'Krager¯' },
  { code: '4016	', name: 'Drangedal' },
  { code: '4018	', name: 'Nome' },
  { code: '4020	', name: 'Midt-Telemark' },
  { code: '4022	', name: 'Seljord' },
  { code: '4024	', name: 'Hjartdal' },
  { code: '4026	', name: 'Tinn' },
  { code: '4028	', name: 'Kviteseid' },
  { code: '4030	', name: 'Nissedal' },
  { code: '4032	', name: 'Fyresdal' },
  { code: '4034	', name: 'Tokke' },
  { code: '4036	', name: 'Vinje' },
  { code: '4202	', name: 'Grimstad' },
  { code: '4203	', name: 'Arendal' },
  { code: '4204	', name: 'Kristiansand' },
  { code: '4205	', name: 'Lindesnes' },
  { code: '4206	', name: 'Farsund' },
  { code: '4207	', name: 'Flekkefjord' },
  { code: '4211	', name: 'Gjerstad' },
  { code: '4212	', name: 'VegÂrshei' },
  { code: '4213	', name: 'Tvedestrand' },
  { code: '4214	', name: 'Froland' },
  { code: '4215	', name: 'Lillesand' },
  { code: '4216	', name: 'Birkenes' },
  { code: '4218	', name: 'Iveland' },
  { code: '4219	', name: 'Evje og Hornnes' },
  { code: '4220	', name: 'Bygland' },
  { code: '4221	', name: 'Valle' },
  { code: '4222	', name: 'Bykle' },
  { code: '4223	', name: 'Vennesla' },
  { code: '4225	', name: 'Lyngdal' },
  { code: '4226	', name: 'HÊgebostad' },
  { code: '4227	', name: 'Kvinesdal' },
  { code: '4228	', name: 'Sirdal' },
  { code: '4601	', name: 'Bergen' },
  { code: '4602	', name: 'Kinn' },
  { code: '4611	', name: 'Etne' },
  { code: '4612	', name: 'Sveio' },
  { code: '4617	', name: 'Kvinnherad' },
  { code: '4618	', name: 'Ullensvang' },
  { code: '4619	', name: 'Eidfjord' },
  { code: '4620	', name: 'Ulvik' },
  { code: '4621	', name: 'Voss' },
  { code: '4622	', name: 'Kvam' },
  { code: '4623	', name: 'Samnanger' },
  { code: '4625	', name: 'Austevoll' },
  { code: '4626	', name: 'ÿygarden' },
  { code: '4628	', name: 'Vaksdal' },
  { code: '4629	', name: 'Modalen' },
  { code: '4630	', name: 'Osterøy' },
  { code: '4631	', name: 'Alver' },
  { code: '4632	', name: 'Austrheim' },
  { code: '4633	', name: 'Fedje' },
  { code: '4634	', name: 'Masfjorden' },
  { code: '4635	', name: 'Gulen' },
  { code: '4636	', name: 'Solund' },
  { code: '4637	', name: 'Hyllestad' },
  { code: '4640	', name: 'Sogndal' },
  { code: '4641	', name: 'Aurland' },
  { code: '4642	', name: 'LÊrdal' },
  { code: '4644	', name: 'Luster' },
  { code: '4645	', name: 'Askvoll' },
  { code: '4646	', name: 'Fjaler' },
  { code: '4647	', name: 'Sunnfjord' },
  { code: '4648	', name: 'Bremanger' },
  { code: '4649	', name: 'Stad' },
  { code: '4650	', name: 'Gloppen' },
  { code: '4651	', name: 'Stryn' },
  { code: '5001	', name: 'Trondheim - Tråante' },
  { code: '5006	', name: 'Steinkjer' },
  { code: '5007	', name: 'Namsos - NÂavmesjenjaelmie' },
  { code: '5043	', name: 'Raarvihke - Røyrvik' },
  { code: '5044	', name: 'Namsskogan' },
  { code: '5045	', name: 'Grong' },
];

export async function GET(req: NextRequest, { params }: { params: Promise<{ query: string }> }) {
  const parms = await params;
  const searchFor = parms.query.toUpperCase();
  const returType = req.nextUrl.searchParams.get('type');

  try {
    if (returType === 'object') {
      return new Response(
        JSON.stringify(kommuner.filter((kommune) => kommune.name.toUpperCase().includes(searchFor))),
        { status: 200 }
      );
    } else {
      return new Response(
        JSON.stringify(
          kommuner.filter((kommune) => kommune.name.toUpperCase().includes(searchFor)).map((kommune) => kommune.name)
        ),
        {
          status: 200,
        }
      );
    }
  } catch (err: unknown) {
    logError('/test/opprett/', err);
    return new Response(JSON.stringify({ message: err?.toString() }), { status: 500 });
  }
}
