name: Bygg pull request

on:
  workflow_dispatch:
  # pull_request:
  #   paths-ignore:
  #     - '**.md'

jobs:
  buildDevPullRequest:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-only-build.yml@bb3280552f7e445fffa11e0cbf41087feac4047d # main
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      cluster: dev-gcp
      linting: true
