name: Bygg pull request

on:
  workflow_dispatch:
  # pull_request:
  #   paths-ignore:
  #     - '**.md'

jobs:
  buildDevPullRequest:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-only-build.yml@0968ded01ca23f7b053a356f5f6b78df919d56fb # main
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      cluster: dev-gcp
      linting: true
